### ISSUE TITLE
[Bug] Private messages

### ISSUE THREAD

**Issue by nicuch** [LOOHP/InteractiveChat#1]
Hello!
I have an ugly (and kind of strange) bug with private messages (from essentials, I didn't test for others).
So, when a player send a private message to another player with the [inv] or any tag, it shows the message reciver inventory instead of the message sender. That's a bug, because the sender can see someone's inventory.

**Comment by LOOHP** [comment]
The problem is caused by the fact that there is currently nothing in the code distinguishing who send a private message as chat packets don't tell you who sent them. I'm thinking of a reliable way to do this. Tho seems like each way had its flaws.

**Comment by nicuch** [comment]
One way should be to replace [inv] with a random generated text (maybe using UUID.random().toString()) and assign that random UUID to the correct inventory.

**Comment by LOOHP** [comment]
That's a really good idea. Tho event priority will be an important factor, I guess I'll make it an option in the config so users can change them for themselves.

**Comment by nicuch** [comment]
Please be kind to event priorities, there's already an dupe bug because of this plugin in combination with BetterShulkerBoxes. But this time is that plugin fault as the event priority is not set up corectly.
https://github.com/lMartin3/BetterShulkerBoxes/issues/6

**Comment by LOOHP** [comment]
Yea, event priorities had been driving me crazy, dealing with weirdly set up priorities from other plugins. So I thought perhaps letting the user modify it themselves is a better approach.

**Comment by nicuch** [comment]
I didn't have other issue with the event priorities other than the one mentioned earlier. I guess that's happens when I only use essentials for chat formatting, and not other plugins that are good for nothing. But TBH, essentials have some downsides too.

**Comment by LOOHP** [comment]
Private messages should work in the new version, just put the command regex in the config.

**Comment by nicuch** [comment]
Fixed. 💯
