### ISSUE TITLE
No cooldown message

### ISSUE THREAD

**Issue by scottyboii** [LOOHP/InteractiveChat#10]
If someone tries to use one of the placeholders in chat, but is on cooldown there is no message letting the user know, it just doesn't work.
Adding a message to let the user know they're on cooldown would be good.

**Comment by LOOHP** [comment]
I guess we could add an option in the config to block the messages with a cooldown message. However, currently the code for cooldown isn't that well rewritten so perhaps I'll wait until I decide to rewrite it first.

**Comment by scottyboii** [comment]
Yeah it's just annoying having players complaining every day that 'The plugins broken' but it's just the cooldown. Lol

**Comment by LOOHP** [comment]
Will keep this in mind for a future update, closing for now.
