### ISSUE TITLE
1.19 Issue

### ISSUE THREAD

**Issue by YTiceice** [LOOHP/InteractiveChat#100]
I am running plugin on 1.19
InteractiveChat version is `4.2.2.0` and VentureChat is `3.4.1_1.19_patch`
When player send any messages,They can't see their messages and have these errors in the console.
![AddText_06-23-11 51 48](https://user-images.githubusercontent.com/87787929/175448543-1e7c8258-8bce-448e-90a4-b702e0e06340.jpg)
I think it because [The PacketListener here has been renamed](https://github.com/Aust1n46/VentureChat/blob/master/src/main/java/mineverse/Aust1n46/chat/listeners) 
Sorry by using screenshot

**Comment by LOOHP** [comment]
This has already been resolved in 4.2.2.1

**Comment by YTiceice** [comment]
Okay, thanks your reply
