### ISSUE TITLE
1.19 Issue

### ISSUE THREAD

**Issue by YTiceice** [LOOHP/InteractiveChat#101]
I am running plugin on 1.19
InteractiveChat version is `4.2.2.1` and VentureChat is `3.4.1_1.19_patch`
When player send any messages,They can't see their messages and have these errors in the console.
![AddText_06-23-11 39 10](https://user-images.githubusercontent.com/87787929/175454050-9e07ca99-c3e1-40f0-9b4b-ec518ddea033.jpg)
Sorry by using screenshot

**Comment by LOOHP** [comment]
There is more info about this on my discord server. http://dev.discord.loohpjames.com

**Comment by YTiceice** [comment]
Ok
