### ISSUE TITLE
Suggestion: Add an XP or LVL placeholder/msg

### ISSUE THREAD

**Issue by JustAMatt** [LOOHP/InteractiveChat#11]
This could be useful to have players use something like [lvl] or [exp] to display their current lvls or xp points in chat. I was unable to find a way to do it with existing tools.

**Comment by LOOHP** [comment]
I believe these two placeholders from papi does what you want
```
%player_exp%
%player_level%
```
(/papi ecloud download Player)

**Comment by JustAMatt** [comment]
> I believe these two placeholders from papi does what you want
> 
> ```
> %player_exp%
> %player_level%
> ```
> 
> (/papi ecloud download Player)

Thank you very much! LVL works but XP is... not really useful, it's just like 0.something long 🤷 

Any chance you could add compatibility to PlayerVaultsX?

**Comment by LOOHP** [comment]
All of the placeholders from PlaceholderAPI can be used, the completed list is here: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders

**Comment by JustAMatt** [comment]
PlayerVaults doesn't really have that, it's more of a second inventory that can be opened by command.

**Comment by LOOHP** [comment]
Then an addon for player vaults is probably needed for that.

**Comment by JustAMatt** [comment]
Hmmm, I see. Should I comment this to their team?

**Comment by LOOHP** [comment]
You could be I doubt that they will hook into InteractiveChat, You can try to write your own addon tho.

**Comment by JustAMatt** [comment]
Will do. Thank you for your time.
