### ISSUE TITLE
Placeholders are just replaced once in catserver-1.12.2

### ISSUE THREAD

**Issue by IllTamer** [LOOHP/InteractiveChat#111]
As the title says, when I send `[i]`, the placeholder will be replaced with the following pattern and broadcast to all players. 
![3WQHI WL5QLK9$~3S99VE%W](https://user-images.githubusercontent.com/78360471/184812129-5d595830-b4b2-4314-afad-ca6b14099494.png)
The correct situation should be that the pattern is replaced by the item Component to be displayed when chat package is sent. 
(Just like this picture shows. placeholder will be invalid in chat, but will be displayed normally in console)
![img](https://user-images.githubusercontent.com/78360471/184812169-de65480c-8cdb-4025-ac3b-ee77e2e5115b.png)
I tested the version of spigot-1.16.4 and found that this situation only occurs in catserver-1.12.2 (Not just placeholders like `[i]`, `[inv]`, `[e]` are the same.)

**Comment by LOOHP** [comment]
![Screenshot_20220816-155124_Discord.jpg](https://user-images.githubusercontent.com/22975196/184826947-067ec928-ae9f-4e97-808d-85b5eebe3464.jpg)

**Comment by IllTamer** [comment]
Well... I tried all the priorities of Chat but none of them worked. orz (The server only loads the InteractiveChat related plugins)

There's the link to get the server core. [[click]](http://www.illtamer.com/resource/source/start.jar)

**Comment by LOOHP** [comment]
If it works in Spigot, that means something is not right with ProtocolLib and CatServer. You should contact them.

**Comment by IllTamer** [comment]
> If it works in Spigot, that means something is not right with ProtocolLib and CatServer. You should contact them.

It's indeed a catserver problem. I replaced the spigot core of the same version and everything is normal. (That's why I don't like mod+plugin core orz

Thanks again for your help !
