### ISSUE TITLE
ParsePlayer doesn't seem to work

### ISSUE THREAD

**Issue by Cinder4198** [LOOHP/InteractiveChat#113]
The ParsePlayer option for custom placeholders doesn't seem to work like it seems like it should. I assume the way it is suppose to work is that when it's set to "sender" it checks if the sender has the required conditions, and changes the message for everyone, while when having it set to "viewer" it will check the viewer's conditions, and change what is displayed to them to the replacement if they meet the requirements. 

However, it seems like even when it's set to viewer, it still acts like it's set to sender. I assume this is just a bug, but idk if I'm just missing something.

**Comment by LOOHP** [comment]
`viewer` just means that the papi placeholders will be parsed using the viewer player instead of the sender player.
