### ISSUE TITLE
[SUGGESTION] Making the "Custom_Placeholders" section as a folder.

### ISSUE THREAD

**Issue by TeQTabanca** [LOOHP/InteractiveChat#114]
**As seen in the title, it is more logical to make the Custom_Placeholers section into a folder and add more than one .yml file inside the folder. Because I will add the commands and messages of most plugins to the Custom_Placeholders section, the Config.yml section will be opened too late because it will be too dimensional. In addition, it seemed a little silly to determine it with a number, so it makes more sense to write a word that we can understand. I hope this feature will be added as soon as possible.**

**Comment by LOOHP** [comment]
I already got the suggestion on the discord server, you do not have to repeat it here. Thanks!
