### ISSUE TITLE
Log spammed with exceptions under 1.19.2

### ISSUE THREAD

**Issue by satadrive420** [LOOHP/InteractiveChat#115]
This error keeps getting spammed in the logs under purpur 1.19.2.

03.10 01:52:48 [Server] WARN [InteractiveChat] Plugin InteractiveChat v4.2.3.10 generated an exception while executing task 70
03.10 01:52:48 [Server] INFO java.lang.NoSuchFieldError: CUSTOM_CHAT_COMPLETIONS
03.10 01:52:48 [Server] INFO at com.loohp.interactivechat.objectholders.ModernChatCompletionTask.lambda$run$0(ModernChatCompletionTask.java:85) ~[InteractiveChat-4.2.3.10.jar:?]
03.10 01:52:48 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1809]
03.10 01:52:48 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1809]
03.10 01:52:48 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
03.10 01:52:48 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
03.10 01:52:48 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
03.10 01:52:48 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LOOHP** [comment]
You need to update ProtocolLib to the latest dev build
