### ISSUE TITLE
Worldguard problems

### ISSUE THREAD

**Issue by ImperatusMaximus** [LOOHP/InteractiveChat#12]
Everytime i use the command /rg flags following shows up.
I use the default config.yml

[InteractiveChat] Cancelled a chat packet bounded to ImperatusMaximus that is 32075 characters long (Longer than maximum allowed in a chat packet) [THIS IS NOT A BUG]

**Comment by LOOHP** [comment]
Which version of InteractiveChat are you using?

**Comment by ImperatusMaximus** [comment]
This happend on the Version 3.2.5.10 
I saw that you released a 3.2.5.11, will try and see if the problem still remains :)
