### ISSUE TITLE
A bug that caused other users to exit the client from server when entering chat.

### ISSUE THREAD

**Issue by madebygood** [LOOHP/InteractiveChat#120]
![image](https://user-images.githubusercontent.com/43653581/198515649-6c040582-0c73-4890-a5b1-adecd8c9ee3e.png)

This is a bug that has occurred since development version #178.

When entering chat, an error like the picture above occurs.

It doesn't seem to happen in my chat.

It is caused by someone else's chat.

There is no problem with version #177.

**Comment by LOOHP** [comment]
Set one of these
```yaml
Settings:
    ForceUnsignedChatPackets: true
```
or
```yaml
Settings:
    HideServerUnsignedStatus: false
```
