### ISSUE TITLE
Question about "Cancelled a chat packet"

### ISSUE THREAD

**Issue by MisterLolxd2** [LOOHP/InteractiveChat#122]
Can i disable this "[InteractiveChat] Cancelled a chat packet bounded to Misterlolxd2 that is 41006 characters long (Longer than maximum allowed in a chat packet), sending original unmodified message instead! [THIS IS NOT A BUG]" ?

**Comment by LOOHP** [comment]
Debug messages can be hidden via the config option `Options.ShowCancelledNotice`

**Comment by MisterLolxd2** [comment]
I do not mean to disable the message, but to disable this annoying option.

**Comment by LOOHP** [comment]
It's there for a reason, the max length of a chat packet is set by Minecraft and cannot be changed.

**Comment by MisterLolxd2** [comment]
This option just with minecraft has nothing to do and cancels the message when you type the command /plugins xD

**Comment by LOOHP** [comment]
Can you show me your config?

**Comment by MisterLolxd2** [comment]
https://pastebin.com/xvweyBvU

**Comment by LOOHP** [comment]
Config looks fine, in that case, your /plugin output is probably just too long to be sent with the proper json formatting (without using legacy color codes). I guess I could add an option to send messages with legacy color codes if they are too long but until then this is an unfortunate side effect.

**Comment by MisterLolxd2** [comment]
Ok,  thanks for information.
