### ISSUE TITLE
PreviewMaps can cause ghost items

### ISSUE THREAD

**Issue by Pantera07** [LOOHP/InteractiveChat#129]
https://youtu.be/HxVT_jUdw5M

Reproduce:
↓ Press F key
![1](https://user-images.githubusercontent.com/89838384/210126312-020ca5fc-8b74-4f81-a6a0-ed1d465abcd8.png)

I think it will be solved by making PreviewMaps available only when the player has an empty hand.

**Comment by LOOHP** [comment]
I'll just cancel the swap if that happens
