### ISSUE TITLE
Suggestion -> {Item} color

### ISSUE THREAD

**Issue by pintoso** [LOOHP/InteractiveChat#13]
### hello, I want to be able to add colors to {Item}

`Text: '&b[{Item} &bx{Amount}]'`

Before:
![image](https://user-images.githubusercontent.com/26844778/104828238-cf5e8d00-5845-11eb-8d05-dd3dc18fcdc3.png)
After:
![image](https://user-images.githubusercontent.com/26844778/104828311-d33edf00-5846-11eb-957c-bc391a7318f6.png)

Items with custom colors don't change(maybe with an option to disable?)
![image](https://user-images.githubusercontent.com/26844778/104828347-3466b280-5847-11eb-9c18-f577221eba46.png)

**Comment by LOOHP** [comment]
Currently, the item's without custom names automatically get their color through it's rarity. (For example, a beacon is blue) That's why the color you set in the config is overridden.

**Comment by pintoso** [comment]
So maybe an option to ignore the default item color will solve(?)
is a simpler solution for those who want to maintain the color style of the players' chat

**Comment by LOOHP** [comment]
I'll consider making that an option in a future update. Closing this for now.
