### ISSUE TITLE
Possible plugin incompatibility (CommandTimer)

### ISSUE THREAD

**Issue by MCHalfAssed** [LOOHP/InteractiveChat#131]
When I install this plugin: CommandTimer https://github.com/titivermeesch/CommandTimer , I'm not able to send input into the chat when Command Timer asks for it. It says "Enter your new task name", I type it in, and I just send a message to chat instead of going back into CMT. (I uninstalled InteractiveChat and CMT worked normally again).

It looks like InteractiveChat is overriding something important for CMT, but after going in the config, I'm not sure what it is or what to change. I was hoping you could give some input?

Also, here's the config for InteractiveChat 🙂
[InteractiveChat_config.txt](https://github.com/titivermeesch/CommandTimer/files/10329384/InteractiveChat_config.txt)

I also have an issue open with CommandTimer as well: https://github.com/titivermeesch/CommandTimer/issues/177

**Comment by LOOHP** [comment]
Try updating to 4.2.5.3

**Comment by MCHalfAssed** [comment]
Will do! I will install and test later tonight, and then report back. 

Thank you!

**Comment by MCHalfAssed** [comment]
After installing  4.2.5.3, this issue is fixed. Thank you!
