### ISSUE TITLE
Default settings for coordinates on hover, etc.

### ISSUE THREAD

**Issue by wellnesscookie** [LOOHP/InteractiveChat#133]
Greetings,

This is a request for change. Many times we have experienced an issue where if we left the default option for `PlayerNameToolTip`, on our factions or similiar server, every player could see other people's coordinates just by hovering mouse to their name. 

Many people use these plugins on servers like factions, and this **should not be** an option that is set to true by default. Please make it false by default, because these can have serious consequences for some people that host servers. There is a reason why Minecraft itself does not make public of other player's coordinates....

**Comment by LOOHP** [comment]
The default config's options partly exist to showcase the possibility of the plugin. Since servers are free to configure the hover text to whatever suits their use case, I feel like it is the responsibility of server owners to configure plugins before applying to their production server.

**Comment by wellnesscookie** [comment]
Sure, there are benefits on both sides, but people like plugins out of the box without worrying about safety and this is a major change that if NOT set to false by default, at least should be explicitly warning or showing users that it potentially could have unwanted consequences. Marketing on developer's side should not be done by turning features as they wish, because if someone installed a plugin of yours, it's because they already found that you have something that they were in need of.
