### ISSUE TITLE
[SUGGESTION] Add support for nickname mentions

### ISSUE THREAD

**Issue by JustJP2K** [LOOHP/InteractiveChat#14]
If you mention a players nick or full name you get notified. 
Currently its only actual name and doesnt support nicknames

Would be a nice addition :)

**Comment by LOOHP** [comment]
Currently, the plugin supports essential nicknames. Which plugin's nickname are you referring to?

**Comment by JustJP2K** [comment]
> 
> 
> Currently, the plugin supports essential nicknames. Which plugin's nickname are you referring to?

essentials nicknames, lol :P

**Comment by LOOHP** [comment]
Merging with #16
