### ISSUE TITLE
Default placeholder values

### ISSUE THREAD

**Issue by Uncroww** [LOOHP/InteractiveChat#143]
So everything's said in the title. 
Here is a picture from when you hover over the name of someone who joined the server : https://ibb.co/TtnqpCZ
Here are pictures from when you type [inv] in the chat : https://ibb.co/Sv8nL0N and https://ibb.co/2sLsPmp

Oh yeah and for whatever reason when you type a message with [inv] in it, the hovering over your username looks like this : https://ibb.co/r6PmPkQ
But when it is a normal message not containing any commands from interactivechat it looks like this : https://ibb.co/xGrBJBZ

This problem even transfers within InteractiveChat DiscordSRV Addon since when the command [inv] is executed, it can't figure out the name of the player : https://ibb.co/yFqCn29

I haven't touched the config file for now and I have multiple plugins which are DiscordSRV Emotecraft InteractiveChat InteractiveChatDiscordSrvAddon JEXT-Reborn PlaceholderAPI ProtocolLib 5.0 SkinsRestorer and Vault.

The server is a Spigot server in 1.19.4.

**Comment by LOOHP** [comment]
You need to download the relevant placeholder API expansion to use PAPI placeholders. For example, to use `%player_name%`, you need to:
```
/papi ecloud download player
/papi reload
`
