### ISSUE TITLE
[SUGGESTION] Add events e.g. hover events to prefixes and suffixes

### ISSUE THREAD

**Issue by JustJP2K** [LOOHP/InteractiveChat#15]
Would be so nice to have hover events for prefixes and suffixes so it could give you more info to a specific rank, title etc

**Comment by LOOHP** [comment]
Unfortunately, InteractiveChat does not know which part of the chat is a "prefix". However, I guess you can add all of your prefixes as a separate placeholder so that the plugin will recognize and add hover messages on it.

**Comment by JustJP2K** [comment]
> 
> 
> Unfortunately, InteractiveChat does not know which part of the chat is a "prefix" or a "suffix". However, I guess you can add all of your prefixes as a separate placeholder so that the plugin will recognize and add hover messages on it.

sounds good. thanks :3
