### ISSUE TITLE
Different version servers on same network.

### ISSUE THREAD

**Issue by andrewkm** [LOOHP/InteractiveChat#17]
We are having issues getting this to work on a network where we have both 1.16 servers and 1.12 servers.
When on the 1.12 server, cross chat item display is shooting errors:
https://pastebin.com/raw/Mi4iiDkE

Is there any way to work around this?
Or would we be forced to not use the plugin on our 1.12 servers?

**Comment by LOOHP** [comment]
I've added a workaround for this issue in 3.2.7.0 The errors should go away.
However, certain features of an item cannot be shared at the moment (like enchantments and lore etc.) I will try to overcome this limitation bought by NBT changes over different version if I can come up with a good way to do so.

**Comment by andrewkm** [comment]
Awesome, I will be testing this shortly.
I am however noticing the below startup issue with latest version on the Bungee side.
https://github.com/LOOHP/InteractiveChat/issues/19

**Comment by andrewkm** [comment]
@LOOHP 
It is acting much better now.
The errors and funky sh** is now gone cross server.
I noticed this in the config however:

`  BungeecordUnknownItem:
    ReplaceItem: BARRIER
    DisplayName: '&cUnknown Item {Type}'
    Lore:
    - '&7Unable to parse item'
    - '&7This is likely to be an item that'
    - '&7does not exist in this version of Minecraft'`
However, I am not seeing any barriers.
Example:
https://i.imgur.com/Xl8wNTZ.jpeg

To the left you have a 1.16.5 server
To the right you have a 1.12.2 server

The left user presented their [inv]
The right user sees a blank space as opposed to the barrier block you intended.

Past that, as it seems right now, initial tests are looking good.
Will continue testing and let you know if we find any issues.

Feel free to close this issue and have me report new ones if you prefer that. :)

**Comment by andrewkm** [comment]
Perhaps I spoke too soon. Some barriers do show:
https://i.imgur.com/Fqzb1UG.png

It looks like items that existed in 1.12.2 but got a name change are the ones being shown as nothing (the issue).
Meanwhile, as with the above screenshot, netherite items do show as barrier blocks on 1.12.2 :)

**Comment by LOOHP** [comment]
Which item is being show as barrier but should exist? (I can't hover on the image and see lel)

**Comment by andrewkm** [comment]
Video:
https://youtu.be/bz7xoOHwQWc
