### ISSUE TITLE
1.8.8 Mention Error!

### ISSUE THREAD

**Issue by Justsean2** [LOOHP/InteractiveChat#18]
I run a 1.8.8 minecraft server and when a player gets mentioned in chat it doesn't work and it returs an error to console any idea why?

25.01 15:52:54 [Server] ERROR Could not pass event AsyncPlayerChatEvent to InteractiveChat v1.4.12
25.01 15:52:54 [Server] INFO org.bukkit.event.EventException
25.01 15:52:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
25.01 15:52:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
25.01 15:52:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
25.01 15:52:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
25.01 15:52:54 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
25.01 15:52:54 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
25.01 15:52:54 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
25.01 15:52:54 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
25.01 15:52:54 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
25.01 15:52:54 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
25.01 15:52:54 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
25.01 15:52:54 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
25.01 15:52:54 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.sendTitle(Ljava/lang/String;Ljava/lang/String;III)V
25.01 15:52:54 [Server] INFO at com.loohp.interactivechat.Events.LegacyEvents.onMention(LegacyEvents.java:151) ~[?:?]
25.01 15:52:54 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
25.01 15:52:54 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
25.01 15:52:54 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
25.01 15:52:54 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
25.01 15:52:54 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.8.8.jar:git-Spigot-6abac0c-9935adc]
25.01 15:52:54 [Server] INFO ... 11 more

**Comment by LOOHP** [comment]
`InteractiveChat v1.4.12` Emm..
This version of InteractiveChat is really really old...
Perhaps try updating to the latest version and see if it works?

**Comment by Justsean2** [comment]
Oh haha, my apologies I downloaded it via apex and didn't even think to check the spigot haha

**Comment by Justsean2** [comment]
I just updated and I still get an error... this one is just on startup tho.

25.01 18:32:12 [Server] INFO Enabling InteractiveChat v3.2.7.2
25.01 18:32:13 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.ItemStack.<init>(net.minecraft.server.v1_8_R3.NBTTagCompound)
25.01 18:32:13 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3082)
25.01 18:32:13 [Server] WARN at java.lang.Class.getDeclaredConstructor(Class.java:2178)
25.01 18:32:13 [Server] WARN at com.loohp.interactivechat.Utils.ItemNBTUtils.setup(ItemNBTUtils.java:32)
25.01 18:32:13 [Server] WARN at com.loohp.interactivechat.InteractiveChat.onEnable(InteractiveChat.java:283)
25.01 18:32:13 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
25.01 18:32:13 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
25.01 18:32:13 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
25.01 18:32:13 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
25.01 18:32:13 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
25.01 18:32:13 [Server] WARN at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
25.01 18:32:13 [Server] WARN at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
25.01 18:32:13 [Server] WARN at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
25.01 18:32:13 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
25.01 18:32:13 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
25.01 18:32:13 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
25.01 18:32:13 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
25.01 18:32:13 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
25.01 18:32:13 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
25.01 18:32:13 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by Justsean2** [comment]
Without using plugman I still get errors as well: https://pastebin.com/rbgND1vW

**Comment by LOOHP** [comment]
Should be fixed in 3.2.8.2

**Comment by Justsean2** [comment]
I loaded the new version (3.2.8) and still several errors on startup..
27.01 15:48:05 [Server] WARN Exception in thread "Craft Scheduler Thread - 3" 
27.01 15:48:05 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin InteractiveChat v3.2.8.2 generated an exception while executing task 243
27.01 15:48:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
27.01 15:48:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
27.01 15:48:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
27.01 15:48:05 [Server] INFO at java.lang.Thread.run(Thread.java:748)
27.01 15:48:05 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/KeybindComponent
27.01 15:48:05 [Server] INFO at com.loohp.interactivechat.Listeners.ChatPackets.processPacket(ChatPackets.java:155)
27.01 15:48:05 [Server] INFO at com.loohp.interactivechat.Listeners.ChatPackets.access$100(ChatPackets.java:51)
27.01 15:48:05 [Server] INFO at com.loohp.interactivechat.Listeners.ChatPackets$1.lambda$onPacketSending$1(ChatPackets.java:98)
27.01 15:48:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
27.01 15:48:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
27.01 15:48:05 [Server] INFO ... 3 more
27.01 15:48:05 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.KeybindComponent
27.01 15:48:05 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
27.01 15:48:05 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
27.01 15:48:05 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
27.01 15:48:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
27.01 15:48:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
27.01 15:48:05 [Server] INFO ... 8 more
27.01 15:48:05 [Server] WARN Exception in thread "Craft Scheduler Thread - 6" 
27.01 15:48:05 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin InteractiveChat v3.2.8.2 generated an exception while executing task 241
27.01 15:48:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
27.01 15:48:05 [Multicraft] Skipped 18 lines due to rate limit (30/s)
27.01 15:48:05 [Server] WARN Exception in thread "Craft Scheduler Thread - 14" 
27.01 15:48:05 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin InteractiveChat v3.2.8.2 generated an exception while executing task 262
27.01 15:48:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
27.01 15:48:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
27.01 15:48:05 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
27.01 15:48:05 [Server] INFO at java.lang.Thread.run(Thread.java:748)
27.01 15:48:05 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/KeybindComponent
27.01 15:48:05 [Server] INFO at com.loohp.interactivechat.Listeners.ChatPackets.processPacket(ChatPackets.java:155)
27.01 15:48:05 [Server] INFO at com.loohp.interactivechat.Listeners.ChatPackets.access$100(ChatPackets.java:51)
27.01 15:48:05 [Server] INFO at com.loohp.interactivechat.Listeners.ChatPackets$1.lambda$onPacketSending$1(ChatPackets.java:98)
27.01 15:48:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
27.01 15:48:05 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
27.01 15:48:05 [Server] INFO ... 3 more
27.01 15:48:05 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.KeybindComponent
27.01 15:48:05 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
27.01 15:48:05 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
27.01 15:48:05 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
27.01 15:48:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
27.01 15:48:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
27.01 15:48:05 [Server] INFO ... 8 more

**Comment by LOOHP** [comment]
Should be fixed in 3.2.8.3
