### ISSUE TITLE
[Feature Request] Add support for Paper's AsyncChat

### ISSUE THREAD

**Issue by NoltoxGit** [LOOHP/InteractiveChat#187]
Hello,
Can you add the support for the Paper `AsyncChatEvent` and/or `AsyncChatDecorateEvent` in the configuration of your plugin please?
Because you're currently using an old listener: `org.bukkit.event.player.AsyncPlayerChatEvent`. 

Example for a new configuration:
```yml
# Use Paper's async Chat Event
use-async-chat: true/false
```

Thank you so much if you add this! :)

**Comment by LOOHP** [comment]
I think there is a use modern paper events option, does that do what you want?

**Comment by NoltoxGit** [comment]
> I think there is a use modern paper events option, does that do what you want?

Thank you for your reply,
I hadn't noticed that this setting existed, I've just activated it, I'll see on my next reboot if it solves my problem.

**Comment by NoltoxGit** [comment]
> I think there is a use modern paper events option, does that do what you want?

Hello,
After a while (sorry), I just realized that when I activate this parameter, CustomPlaceholders are no longer displayed correctly in the chat :/.

Here's my [config](https://hastebin.com/share/uburucipaz.yaml).
Server version: `Purpur-2134 (MC: 1.20.4)`
Plugin version: 4.2.9.0 (#263)
