### ISSUE TITLE
[bug] Velocity changed the class name after Velocity-3.3.0-SNAPSHOT-328

### ISSUE THREAD

**Issue by half-nothing** [LOOHP/InteractiveChat#188]
![image](https://github.com/LOOHP/InteractiveChat/assets/50048293/b986d7c9-f538-4e6c-bb1d-d01780e2c19c)
Log here:
https://pastebin.mozilla.org/H0ghaOpA
Reason:
Please look at this [commit](https://github.com/PaperMC/Velocity/commit/2ac8751337befd04f4663575f5d752c748384110)

**Comment by LOOHP** [comment]
Yes, but it should already be fixed in the latest dev build.

**Comment by half-nothing** [comment]
I didn't see Jenkins, sorry.
