### ISSUE TITLE
/say command kicks player

### ISSUE THREAD

**Issue by N0rule** [LOOHP/InteractiveChat#192]
Server: Purpur 1.20.1
when player use /say <text>
it kicks player and gives this error
![image](https://github.com/LOOHP/InteractiveChat/assets/30196774/f36fc5ba-7def-4091-8ffd-1c24fd8a16f6)

![image](https://github.com/LOOHP/InteractiveChat/assets/30196774/0a831241-5b6b-4a06-87d3-9bf7160edb5a)

[config file: config.txt](https://github.com/LOOHP/InteractiveChat/files/14337912/config.txt)

**Comment by GsTio86** [comment]
Same error, but I dropped the version back to 4.2.8.0 and everything works fine

**Comment by GsTio86** [comment]
After testing, it is the problem caused by this submission.

https://github.com/LOOHP/InteractiveChat/commit/1ce6abba3fb25b0a55c8d2144bc3357322c8af9c
