### ISSUE TITLE
ExcellentEnchants hook now outdated

### ISSUE THREAD

**Issue by Projecki** [LOOHP/InteractiveChat#197]
Hello,

ExcellentEnchants received a recode to v4.0.0

Now, InteractiveChat will not load on servers with latest ExcellentEnchants plugin due to a bad hook.

Can this hook be updated, or the option to ignore a hook for a specific plugin be added?

Thank you

**Comment by LOOHP** [comment]
ExcellentEnchants hook has been updated in 4.2.10.
