### ISSUE TITLE
Paper update broke InteractiveChat

### ISSUE THREAD

**Issue by Xynrati** [LOOHP/InteractiveChat#198]
I was working on my server, which autoupdates paper. Mid-testing my own plugin, paper updated. Relevant breaking change is https://github.com/PaperMC/paper/commit/9e886c431029a71a97e850bec8c63b0699fd09f2

InteractiveChat is now breaking with 

`20.04 01:38:56 [Server] WARN Plugin InteractiveChat v4.2.9.0 generated an exception while executing task 3739
20.04 01:38:56 [Server] INFO java.lang.IllegalArgumentException: Unexpected type: class io.papermc.paper.adventure.AdventureComponent
20.04 01:38:56 [Server] INFO at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:197) ~[InteractiveChat-4.2.9.0.jar:?]
20.04 01:38:56 [Server] INFO at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$4(RedispatchSignedPacket.java:92) ~[InteractiveChat-4.2.9.0.jar:?]
20.04 01:38:56 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-487]
20.04 01:38:56 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-487]
20.04 01:38:56 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
20.04 01:38:56 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
20.04 01:38:56 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
20.04 01:38:56 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by LOOHP** [comment]
Thanks for the report. It looks like you might not be on the latest dev build. Can you try the latest build on https://ci.loohpjames.com, and if the error still occurs, send that new one?

**Comment by Xynrati** [comment]
I did a fresh download, build 265, and still same issue (and version). I noticed that your changelog on that build was about bumping the adventure version.

**Comment by LOOHP** [comment]
Yes I made some changes, please send the errors produced by the latest build. It will help me identify the issue much easier.

**Comment by Xynrati** [comment]
20.04 05:14:18 [Server] WARN Plugin InteractiveChat v4.2.9.0 generated an exception while executing task 2139
20.04 05:14:18 [Server] INFO java.lang.IllegalArgumentException: Unexpected type: class io.papermc.paper.adventure.AdventureComponent
20.04 05:14:18 [Server] INFO at com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:197) ~[InteractiveChat-4.2.9.0.jar:?]
20.04 05:14:18 [Server] INFO at com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$4(RedispatchSignedPacket.java:92) ~[InteractiveChat-4.2.9.0.jar:?]
20.04 05:14:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-488]
20.04 05:14:18 [Server] INFO at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-488]
20.04 05:14:18 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
20.04 05:14:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
20.04 05:14:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
20.04 05:14:18 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Xynrati** [comment]
Is there a build after 265/4.2.9.0 that i can't see?

**Comment by XLordalX** [comment]
Same issue

**Comment by LOOHP** [comment]
Thanks for the report. It should be fixed in build #266.
