### ISSUE TITLE
1.20.5 Support

### ISSUE THREAD

**Issue by DarkChromaMC** [LOOHP/InteractiveChat#203]
Running [item] for an empty hand or a head from head database plugin, will cause players running on 1.20.5 to be kicked.

![image](https://github.com/LOOHP/InteractiveChat/assets/68839442/d6bc1109-d4c7-4102-b821-ac79b6b0626d)

**Comment by LOOHP** [comment]
We need to wait for ProtocolLib to be updated to 1.20.5 first.

**Comment by LOOHP** [comment]
4.2.10 now supports 1.20.6.
