### ISSUE TITLE
Newest Dev build not allowing for chat messages on Chat Control Red

### ISSUE THREAD

**Issue by ClxdyWindows** [LOOHP/InteractiveChat#209]
https://paste.helpch.at/wezijuhohe.rb

**Comment by LOOHP** [comment]
Which version & build of PaperMC are you running?

**Comment by ClxdyWindows** [comment]
@LOOHP purpur 1.20.4 build #2155, not sure what paper update that was

**Comment by LOOHP** [comment]
That might be the reason why, it looks like that purpur build is not up to date with paper upstream. Try updating to the latest purpur build for 1.20.4,

**Comment by ClxdyWindows** [comment]
Yep you are correct!
