### ISSUE TITLE
Linking another users [inv] [ender] and [item] if sent at the same time

### ISSUE THREAD

**Issue by andrewkm** [LOOHP/InteractiveChat#21]
Environment:
Paper Spigot 1.16.5: Build 445 https://papermc.io/downloads#Paper-1.16
InteractiveChat 3.2.8.2 Build 104 https://ci.loohpjames.com/job/InteractiveChat/
WorldGuard 7.0.5 Build 2098 https://builds.enginehub.org/job/worldguard?branch=master

One of our users sends the following advertisement constantly:
https://pastebin.com/raw/m3PucXbR

The username is BobbyBlack, yet for some odd reason on like 22966 it linked a different users enderchest.
Happened just once and we are unsure how to reproduce. Logs were examined prior and after the event and we see nothing out of the blue that would cause this.

Result:
https://i.imgur.com/S5CQBiN.png

**Comment by andrewkm** [comment]
Found proper reproduction.
You can do this with anything [item] [inv] [ender]
All it takes is for two users to run the command at the same time.
Such as [item] at the same time, etc.

And this isn't even that rare, with our advertising channel, and several active users / markets, this is constantly happening. :(
https://ecocitycraft.com/forum/threads/problem-with-the-new-ender.208628/ - Feel free to read through the user report.

**Comment by LOOHP** [comment]
Oh I see... I have an idea of what might have caused it but I am not very sure. Therefore, I've created a dev build with a few changes. Can you give it a try and see if the fix works for you?
[InteractiveChat-3.2.9.8.zip](https://github.com/LOOHP/InteractiveChat/files/5911099/InteractiveChat-3.2.9.8.zip)

**Comment by andrewkm** [comment]
@LOOHP This is still happening, even on your development build above.

**Comment by LOOHP** [comment]
Yea I know, I'm thinking of a way to fix this rn. As I'm still not really sure which part of the code is causing it.

**Comment by LOOHP** [comment]
Feel free to give version 3.2.10.4 a try and see if the issue is fixed with the new sender finder!

**Comment by andrewkm** [comment]
Fixed. Confirmation via dozens of automated bot tests.
