### ISSUE TITLE
[1.20.6] "Unknown item 'minecraft:' at position 0" Console Message when Using [inv]

### ISSUE THREAD

**Issue by Pantera07** [LOOHP/InteractiveChat#211]
Using [inv] placeholder on the 1.20.6 server will result in an error.

InteractiveChat Build#272
InteractiveChat-DiscordSRV-Addon Build#307

```
[22:43:55 ERROR]: [org.bukkit.craftbukkit.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]
[22:43:55 ERROR]: [org.bukkit.craftbukkit.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]
```

**Comment by LOOHP** [comment]
I am aware of this error. However, it seems to have no effect on any features so it made it very difficult to find out what is the cause of it. Please let me know if you think it might be associated with any bugs or side-effects.
