### ISSUE TITLE
Is it possible to make it work with some proxy chat plugin like HuskChat?

### ISSUE THREAD

**Issue by SeemWind** [LOOHP/InteractiveChat#213]
[HuskChat](https://github.com/WiIIiam278/HuskChat)

I use this plugin in proxy, and it only handle chat in proxy side as velocity or bungee plugin, doesn't send message to backend server.
﻿

**Comment by LOOHP** [comment]
How does it not work right now? Are you on the latest dev build?

**Comment by SeemWind** [comment]
> How does it not work right now? Are you on the latest dev build?

As I said, this plugin only handle message in proxy, I think interactivechat need some special method to support

**Comment by LOOHP** [comment]
I've tested with HuskChat before and using stuff like [item] does work.

**Comment by SeemWind** [comment]
I use channel whose scope is GLOBAL, did you try it?

**Comment by LOOHP** [comment]
I used the default config. Which Minecraft version are your backend servers?

**Comment by LOOHP** [comment]
Then it is probably not working because of the issue on ProtocolLib I quoted above.

**Comment by SeemWind** [comment]
Well, this time everything works correctly, thank you

**Comment by SeemWind** [comment]
By the way, folia support please🙏

**Comment by Yaosanqi137** [comment]
I have same issue (using huskchat in velocity) althought i updated my protocollib(5.3.0) and i also use lastest version of interactivechat(4.2.16.0) in my backen servers, it still can't parse the placeholders

**Comment by SeemWind** [comment]
> I have same issue (using huskchat in velocity) althought i updated my protocollib(5.3.0) and i also use lastest version of interactivechat(4.2.16.0) in my backen servers, it still can't parse the placeholders

huskchat归档了，我已经不再用huskchat了

**Comment by Yaosanqi137** [comment]
1. 

> > I have same issue (using huskchat in velocity) althought i updated my protocollib(5.3.0) and i also use lastest version of interactivechat(4.2.16.0) in my backen servers, it still can't parse the placeholders
> 
> huskchat归档了，我已经不再用huskchat了

那请问当时您当时是如何解决这个问题的呢？

**Comment by Yaosanqi137** [comment]
> > > > I have same issue (using huskchat in velocity) althought i updated my protocollib(5.3.0) and i also use lastest version of interactivechat(4.2.16.0) in my backen servers, it still can't parse the placeholders
> > > 
> > > 
> > > huskchat归档了，我已经不再用huskchat了
> > 
> > 
> > 那请问当时您当时是如何解决这个问题的呢？
> 
> 你在代理上装了ic，并且打开了ic的跨服模式吗

打开了

**Comment by SeemWind** [comment]
> > > > > I have same issue (using huskchat in velocity) althought i updated my protocollib(5.3.0) and i also use lastest version of interactivechat(4.2.16.0) in my backen servers, it still can't parse the placeholders
> > > > 
> > > > 
> > > > huskchat归档了，我已经不再用huskchat了
> > > 
> > > 
> > > 那请问当时您当时是如何解决这个问题的呢？
> > 
> > 
> > 你在代理上装了ic，并且打开了ic的跨服模式吗
> 
> 打开了

不记得当初的情况了，而且现在也不一定适用了

**Comment by Yaosanqi137** [comment]
> > > > > > I have same issue (using huskchat in velocity) althought i updated my protocollib(5.3.0) and i also use lastest version of interactivechat(4.2.16.0) in my backen servers, it still can't parse the placeholders
> > > > > 
> > > > > 
> > > > > huskchat归档了，我已经不再用huskchat了
> > > > 
> > > > 
> > > > 那请问当时您当时是如何解决这个问题的呢？
> > > 
> > > 
> > > 你在代理上装了ic，并且打开了ic的跨服模式吗
> > 
> > 
> > 打开了
> 
> 不记得当初的情况了，而且现在也不一定适用了，也许可以看看huskchat的文档 https://william278.net/docs/huskchat/Backend-Chat-Entry https://william278.net/docs/huskchat/Channels

好吧，感谢回答
