### ISSUE TITLE
[ERROR] Newest version is not linking with DiscordSRV

### ISSUE THREAD

**Issue by JustJP2K** [LOOHP/InteractiveChat#23]
Here is the Error:
https://paste.helpch.at/mufesezuwo.sql

**Comment by LOOHP** [comment]
Did you update interactivechatdiscordsrvaddon to the latest version as well?

**Comment by JustJP2K** [comment]
ah thats probably it. i didnt get an alert on spigot that there was also a new discordsrvaddon update

**Comment by JustJP2K** [comment]
on a side note, did you have time to look into the towny chat incompatibility?

**Comment by LOOHP** [comment]
> ah thats probably it. i didnt get an alert on spigot that there was also a new discordsrvaddon update

You can always run `/ic update` and `/icd update` to check



> on a side note, did you have time to look into the towny chat incompatibility?

Not yet, I'll look into that next week probably.

**Comment by JustJP2K** [comment]
sounds good. thanks :)
