### ISSUE TITLE
/ic events menu on Bedrock -> Cheats aren't enabled in this world.

### ISSUE THREAD

**Issue by bobhenl** [LOOHP/InteractiveChat#232]
Hello, when I try to use /ic events menu (or only /ic or /interactivechat)
I get this error
![image](https://github.com/user-attachments/assets/157e7f15-07dd-4a19-9efd-ca757cc437a9)

**Comment by bobhenl** [comment]
Still not solved @LOOHP

**Comment by LOOHP** [comment]
Perhaps something needs to be enabled on Geyser's config? Could be due to the bedrock client thoughts cheats aren't enabled on the world so it rejects all commands.

**Comment by bobhenl** [comment]
In the past they told that this error is caused by the:
```yml

# Allows Xbox achievements to be unlocked.
xbox-achievements-enabled: true

**Comment by LOOHP** [comment]
Does `/ic events` work if the xbox achievement option is set to `false`?

**Comment by bobhenl** [comment]
It got fixed somehow even when it's true again, not sure how it got fixed
