### ISSUE TITLE
ItemDisplay will cause some commands to be unusable 

### ISSUE THREAD

**Issue by nicklly** [LOOHP/InteractiveChat#30]
Plugins Version:  3.2.9.13
Residence: 4.9.2.6

ItemDisplay:
  Item:
    Enabled: false
    CaseSensitive: true
    Keyword: '[item]'
    Aliases:
    - (?i)([i])
    Text: '&7[&b{Item}&7]'
    InventoryTitle: '%player_name% 物品'
    Cooldown: 0
    GUIEnabled: false
    Frame:
      Primary: STAINED_GLASS_PANE:2
      Secondary: STAINED_GLASS_PANE:15
    Description: '&a在聊天栏上显示你手上的物品!'

if set the Enabled is true, will cause some commands to be unusable :
/res info 
/res listall
/res list
The above three commands will be displayed /command help
/resadmin (in game will display 'unknow command')

example:
![QQ截图20210214082358](https://user-images.githubusercontent.com/17716585/107865122-6ac33c00-6e9e-11eb-98c0-3ebfc80fe242.png)
![QQ截图20210214082414](https://user-images.githubusercontent.com/17716585/107865081-10c27680-6e9e-11eb-9363-8d5c2eadba56.png)
![QQ截图20210214082330](https://user-images.githubusercontent.com/17716585/107865084-11f3a380-6e9e-11eb-95cc-6925dd394cfc.png)
![QQ截图20210214082347](https://user-images.githubusercontent.com/17716585/107865085-128c3a00-6e9e-11eb-93f4-1069de17f349.png)

**Comment by LOOHP** [comment]
Can you show me your InteractiveChat config?

**Comment by nicklly** [comment]
you can see that from https://pastebin.com/B4EEfML3

**Comment by LOOHP** [comment]
Try changing this line from CommandToParse from `- (?i)/r.*` to `- (?i)/r .*` (one extra space)

**Comment by nicklly** [comment]
it done, the Aliases will be block some command, `- (?i)([i])` already blocked

**Comment by LOOHP** [comment]
Not quite understand what you mean. Soo.. did that change work?

**Comment by nicklly** [comment]
yes
