### ISSUE TITLE
Incorrect Permission Handling

### ISSUE THREAD

**Issue by scottyboii** [LOOHP/InteractiveChat#32]
Hey!

It appears from my testing that having "interactivechat.chatcolor.translate" also allows access formatting codes.
This should not be the case, chat formatting codes should be under "interactivechat.customfont.translate".

**Comment by LOOHP** [comment]
Custom font is the new font feature added in 1.16
Formatting codes includes both colors and formatting, which is all called ChatColor in Bukkit/Spigot.
