### ISSUE TITLE
Latest version severely spamming console on every login.

### ISSUE THREAD

**Issue by andrewkm** [LOOHP/InteractiveChat#33]
Console spamming on every player login.:

`[14:25:25] [Craft Scheduler Thread - 6/INFO]: {"extra":[{"text":"&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&aConnecting &a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&ato &a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&aanarchy &a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&a&aserver..."}],"text":""}`

Verified breaking commit:
https://github.com/LOOHP/InteractiveChat/commit/1a989c6f8d9f82300dfe64ed2bc233c63bb7a396

Problem here:
https://github.com/LOOHP/InteractiveChat/commit/1a989c6f8d9f82300dfe64ed2bc233c63bb7a396#diff-c21eda405e8f2f7768f1a4d1f95e029bb4b5b7969c292db06024e8af2f4b0114R94

**Comment by LOOHP** [comment]
Oops, removed in the next commit.
