### ISSUE TITLE
Unhandled PacketSending

### ISSUE THREAD

**Issue by TheCiROMG** [LOOHP/InteractiveChat#34]
[09:52:44] [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
[09:52:44] Parameters:
net.minecraft.server.v1_16_R3.PacketPlayOutChat@6bd113d9[
a=<null>
components=<null>
b=SYSTEM
c=00000000-0000-0000-0000-000000000000
]

This appeared after updating to paper 470 1.16.5

Sent messages do not appear in the game but do appear on the console

**Comment by LOOHP** [comment]
I believe this is a paper bug, it'd be best to report this is papermc.

**Comment by LOOHP** [comment]
PaperMC/Paper#5220

**Comment by andrewkm** [comment]
@LOOHP 
Same problem here.
Running latest Paper 484 via https://github.com/PaperMC/Paper/commit/d5cb9308f20639fd080ff0cc8c151396325ea7ac
Apparently this is a ProtocolLib issue actually.

**Comment by LOOHP** [comment]
Should be fixed after dmulloy2/ProtocolLib#1103
