### ISSUE TITLE
All players can use custom modules even if permission is false.

### ISSUE THREAD

**Issue by andrewkm** [LOOHP/InteractiveChat#35]
For some reason the permission **interactivechat.module.custom** simply doesn't work.
No matter what, all players can use custom modules.

Paper Build **484**
Luckperms Build **5.2.116**
InteractiveChat Build **123**

All other permissions work correctly such as **interactivechat.module.inventory** and **interactivechat.module.enderchest**.

**Comment by LOOHP** [comment]
The custom module has one permission per placeholder (If use permission is enabled in the config) 
**interactivechat.module.custom.<index of placeholder>**

**Comment by andrewkm** [comment]
Ahh, oops, missed that config option. Thanks!
