### ISSUE TITLE
Hex color in player hover from vault prefix not coloring

### ISSUE THREAD

**Issue by hawkfalcon** [LOOHP/InteractiveChat#38]
I'm using %vault_prefix% in the player hover text, and my prefix contains a hex color code e.g. &#FFFFFF. It's showing up as that in the hover, not as the colored text

**Comment by hawkfalcon** [comment]
Hmm, I'm finding this in more places. Hex chat is not working for ReplaceText either

**Comment by hawkfalcon** [comment]
I tried it with &x&f&f&f&f&f&f. It works with chat, but the text loaded from vault_prefix isn't colored

**Comment by hawkfalcon** [comment]
I figured it out. Your regex is parsing it weird when there's no text after a &x&...., it's parsing the color codes individually like &f
You can repro this:
If I type 
&x&0&6&5&2&D&DTEXT in chat, I get blue text

If I type 
&x&0&6&5&2&D&D without text, I get &x&D&D

**Comment by hawkfalcon** [comment]
I'm wrong. It still does it within the hover meta when I add text. It's the wrong color, which is super weird. I'm now guessing it's something with how color is parsed from Placeholder API strings

**Comment by LOOHP** [comment]
At the moment, the plugin doesn't have any code to parse the `&#123456` color format, which is probably the reason why that doesn't work. 

Indeed I forgot to convert the rgb color codes (`&x&0&6&5&2&D&D` format) in the hover events, will get that fixed soon.

**Comment by LOOHP** [comment]
[InteractiveChat-3.2.10.9-SNAPSHOT.zip](https://github.com/LOOHP/InteractiveChat/files/6101940/InteractiveChat-3.2.10.9-SNAPSHOT.zip)
Can you give this build a try?

**Comment by hawkfalcon** [comment]
Fixed! Thank you so much
