### ISSUE TITLE
Chat message with <chat=UUID> at the end

### ISSUE THREAD

**Issue by NeadApTar** [LOOHP/InteractiveChat#45]
![image](https://user-images.githubusercontent.com/34768994/112058695-956e7780-8b63-11eb-91ff-8721cd67be03.png)

Sometimes this appears in some messages

Build 176
WaterFall + Paper
Chat plugin -> [UltimateChat](https://www.spigotmc.org/resources/ultimatechat-1-7-1-16.23767/)

**Comment by andrewkm** [comment]
@NeadApTar what build are you using (of interactive chat?)

**Comment by NeadApTar** [comment]
I wrote, build 176

**Comment by andrewkm** [comment]
Try using 178.
Also make sure UseAccurateSenderParser is true everywhere (Bungee and Backend).

**Comment by NeadApTar** [comment]
Nope, not fixed

**Comment by andrewkm** [comment]
How about with accurate parser to false everywhere?

**Comment by LOOHP** [comment]
Can you give this build a try? [Download](https://cdn.discordapp.com/attachments/804071066783186966/823905822941380678/InteractiveChat-3.2.11.7.jar)

**Comment by NeadApTar** [comment]
```
23.03 16:38:12 [Server] WARN com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2935 path $
23.03 16:38:12 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:65)
23.03 16:38:12 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:45)
23.03 16:38:12 [Server] WARN at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48)
23.03 16:38:12 [Server] WARN at com.loohp.interactivechat.Modules.ProcessBungeeRequestedMessage.processAndRespond(ProcessBungeeRequestedMessage.java:33)
23.03 16:38:12 [Server] WARN at com.loohp.interactivechat.BungeeMessaging.BungeeMessageListener.lambda$onPluginMessageReceived$2(BungeeMessageListener.java:215)
23.03 16:38:12 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
23.03 16:38:12 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
23.03 16:38:12 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
23.03 16:38:12 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
23.03 16:38:12 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
23.03 16:38:12 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)
23.03 16:38:12 [Server] WARN Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2935 path $
23.03 16:38:12 [Server] WARN at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
23.03 16:38:12 [Server] WARN at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
23.03 16:38:12 [Server] WARN at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
23.03 16:38:12 [Server] WARN at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
23.03 16:38:12 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:60)
23.03 16:38:12 [Server] WARN ... 10 more
```
and bungee messages are not displayed

**Comment by LOOHP** [comment]
> ```
> 23.03 16:38:12 [Server] WARN com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2935 path $
> 23.03 16:38:12 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:65)
> 23.03 16:38:12 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:45)
> 23.03 16:38:12 [Server] WARN at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48)
> 23.03 16:38:12 [Server] WARN at com.loohp.interactivechat.Modules.ProcessBungeeRequestedMessage.processAndRespond(ProcessBungeeRequestedMessage.java:33)
> 23.03 16:38:12 [Server] WARN at com.loohp.interactivechat.BungeeMessaging.BungeeMessageListener.lambda$onPluginMessageReceived$2(BungeeMessageListener.java:215)
> 23.03 16:38:12 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
> 23.03 16:38:12 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
> 23.03 16:38:12 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> 23.03 16:38:12 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 23.03 16:38:12 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 23.03 16:38:12 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)
> 23.03 16:38:12 [Server] WARN Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2935 path $
> 23.03 16:38:12 [Server] WARN at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
> 23.03 16:38:12 [Server] WARN at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
> 23.03 16:38:12 [Server] WARN at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
> 23.03 16:38:12 [Server] WARN at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
> 23.03 16:38:12 [Server] WARN at com.google.gson.JsonParser.parse(JsonParser.java:60)
> 23.03 16:38:12 [Server] WARN ... 10 more
> ```
> 
> and bungee messages are not displayed and problem remains

This is from build 178 or the build I just linked above?

**Comment by NeadApTar** [comment]
Link above

**Comment by LOOHP** [comment]
[How about this one?](https://drive.google.com/file/d/1ef7JZy0cJu9gPawQf4ir-3rtFD5ft120/view?usp=sharing)

**Comment by NeadApTar** [comment]
Nope, error is fixed, bungee messages are displayed, but tag at the end still remainsbut it still remains
![image](https://user-images.githubusercontent.com/34768994/112178667-9e625600-8c02-11eb-9f1e-6deadbe3a0b7.png)

**Comment by LOOHP** [comment]
Try setting `UseAccurateSenderParser` to false everywhere (Bungee and Backend)

**Comment by NeadApTar** [comment]
Hmm, everything seems to be fine

**Comment by andrewkm** [comment]
So you got it fixed?

**Comment by NeadApTar** [comment]
Yup. I need some time to confirm this exactly. If everything is okay, then I will close issue
