### ISSUE TITLE
Dupe issue with [item]

### ISSUE THREAD

**Issue by scottyboii** [LOOHP/InteractiveChat#48]
Opening an [i]/[item] menu by clicking on it, and then closing results in the items and glass panes being dropped on the floor.

Paper - git-Paper-445 (MC: 1.16.5)
InteractiveChat - 3.2.11.7
InteractiveChatDiscordSrvAddon - 1.3.5.3
VentureChat - 2.22.1

**Comment by scottyboii** [comment]
[inv] works fine without duping, and the issue still occurs without the srv addon.
Been happening for a few versions too (unsure when specifically)

**Comment by LOOHP** [comment]
Can you elaborate on "closing result in the item"? I don't understand what you mean.

**Comment by scottyboii** [comment]
Closing the GUI that opens when you click on the text in chat by pressing escape.

**Comment by LOOHP** [comment]
Any errors in the console?

**Comment by scottyboii** [comment]
Nothing in console.

**Comment by LOOHP** [comment]
I've tested on Paper 504 and no duping is observed.

**Comment by scottyboii** [comment]
Using venturechat too? I have a feeling it is caused by a conflict with venturechat.

**Comment by LOOHP** [comment]
I'm also using VentureChat, so it's probably not it. Perhaps try performing a binary plugin search?

**Comment by scottyboii** [comment]
I have no clue what that means to be honest haha.

**Comment by LOOHP** [comment]
It means booting up a test server, removing half of the plugins each time, so you can identify which plugin is conflicting quickly.

**Comment by scottyboii** [comment]
Oh, that! Never heard of it referred to as that before haha. Ill try it tomorrow and get back to you! :)

**Comment by scottyboii** [comment]
Apologies for the delay, I finally got around to it and it turns out the issue is a conflict with [ItemSoulBind](https://www.spigotmc.org/resources/itemsoulbind.64541/).

Is there anything you can do about this or would the dev of ItemSoulBind need to fix?

**Comment by LOOHP** [comment]
> Apologies for the delay, I finally got around to it and it turns out the issue is a conflict with [ItemSoulBind](https://www.spigotmc.org/resources/itemsoulbind.64541/).
> I'm on the latest version of that plugin.
> 
> Is there anything you can do about this or would the dev of ItemSoulBind need to fix?

I've just installed that plugin on my test server and I didn't observe any problems. Can you provide me with the exact steps to reproduce conflict?

**Comment by scottyboii** [comment]
Hmm, unless its a config issue with the soulbind?

Without ItemSoulBind everything functions fine. With ItemSoulBind, the item dupes from the GUI from [i].

Steps:
[i] in chat
Click on the item in chat (so it opens GUI)
Press esc

**Comment by LOOHP** [comment]
> Hmm, unless its a config issue with the soulbind?
> 
> Without ItemSoulBind everything functions fine. With ItemSoulBind, the item dupes from the GUI from [i].
> 
> Steps:
> [i] in chat
> Click on the item in chat (so it opens GUI)
> Press esc
> The items are dropped from the GUI

How do I cause the /returnitems to give me items? So I can test the plugin.

**Comment by scottyboii** [comment]
Not sure, I'd presume it takes someone else to try to remove one of your soulbound items from a chest.

**Comment by scottyboii** [comment]
Here's a video https://youtu.be/m_WdMDt4TS4

**Comment by LOOHP** [comment]
Once the PR is merged, the conflict will be resolved.

**Comment by scottyboii** [comment]
Thank you :)
