### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fargus5** [LOOHP/InteractiveChat#5]
Hi, there is the possibility to create for me a very small thing?

I only need a placeholder in Papi where I can set any text with a command in chat.

Like this:

/new <insert multiline text here>

%newtext% = this will be read with the text that I wrote with the minecraft color support.

Are u able to do this?

**Comment by LOOHP** [comment]
This feature seems to be more related to PlaceholderAPI and other chat stuff than InteractiveChat itself.
Feel free to contact me through discord or dm for stuff related to other things!

**Comment by Fargus5** [comment]
I wrote to u on spigot.
