### ISSUE TITLE
Join Messages

### ISSUE THREAD

**Issue by scottyboii** [LOOHP/InteractiveChat#50]
It's me again lol..

Join messages are removed when I have interactive chat on the server for some reason

Our join messages are from chat control.

Is this a setting that I'm missing in interactive chat?

I've tested with InteractiveChat, which results in no join messages.
Without InteractiveChat, which results in join messages as normal.

**Comment by LOOHP** [comment]
Are there any errors in the console?

**Comment by scottyboii** [comment]
Nope, Ill check log files later too.

**Comment by LOOHP** [comment]
Also make sure you are using the latest dev build of InteractiveChat

**Comment by scottyboii** [comment]
Right just checked with 3.2.13.10, issue still occurs.

It does show an error on join on our test server:
https://pastebin.com/Bw40mf6X

**Comment by LOOHP** [comment]
You need to use the latest dev build of protocollib (4.6.1-SNAPSHOT)

**Comment by scottyboii** [comment]
Ah, thank you! That fixed it.
