### ISSUE TITLE
Warning: Backend Server ... is not running a version...

### ISSUE THREAD

**Issue by satyrnhub** [LOOHP/InteractiveChat#53]
Hi. When I join my server, I receive this message in chat:
`[InteractiveChat] Warning: Backend Server Survival is not running a version of InteractiveChat which has the same plugin messaging protocol version as the proxy!`

I am running the same version of InteractiveChat on both the proxy, and each server.

/interactivechatproxy backendinfo:
`Survival -> InteractiveChat: NOT INSTALLED (PM Protocol: -1) | Minecraft: unknown | Ping: 0 ms`

**Comment by satyrnhub** [comment]
Some more information:
Server is running Purpur 1.16.5.
Proxy is running Velocity 1.1.4.

**Comment by LOOHP** [comment]
Do you have server list ping query enabled on your "Survival" server?

**Comment by satyrnhub** [comment]
I'm pretty sure I do, but how exactly would I check if I do?

**Comment by LOOHP** [comment]
I think you can check that in one of the server configs (either server.properties, bukkit.yml or spigot.yml)

**Comment by satyrnhub** [comment]
Query is enabled on port 4002, do I need to change it to a different port?

**Comment by satyrnhub** [comment]
Fixed, forgot to enable Bungeecord in the interactive chat settings the entire time...

**Comment by satyrnhub** [comment]
Having a new issue, I'll create a new report for this one.
