### ISSUE TITLE
InteractiveChat generates an error when a player tries to speak

### ISSUE THREAD

**Issue by baailey** [LOOHP/InteractiveChat#55]
When I try to send a message like 'hi', InteractiveChat errors and my message does not get send to chat, but do get send to console. I've tried deleting the folder too in case it was maybe caused by a config issue. Commands work fine.

`13.05 17:05:39 [Server] ERROR [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
13.05 17:05:39 [Server] INFO java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@6cddaa25 (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@3a381cd4
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1055) ~[?:?]
13.05 17:05:39 [Server] INFO at com.loohp.interactivechat.listeners.OutChatPacket$1.onPacketSending(OutChatPacket.java:187) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:382) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:347) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:317) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:507) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1976) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1949) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2124) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.kyori.adventure.audience.ForwardingAudience.sendMessage(ForwardingAudience.java:65) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:207) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:183) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.broadcastMessage(CraftServer.java:583) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at org.bukkit.Bukkit.broadcastMessage(Bukkit.java:308) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at a4.rule.books.Main$2.run(Main.java:181) ~[?:?]
13.05 17:05:39 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1485) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:422) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1398) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Airplane-"fad74c2"]
13.05 17:05:39 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
13.05 17:05:39 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot clone TextComponentImpl{content="", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="●", style=StyleImpl{color=NamedTextColor{value="#5555ff"}, obfuscated=not_set, bold=not_set, strikethrough=true, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="----------------", style=StyleImpl{color=NamedTextColor{value="#555555"}, obfuscated=not_set, bold=not_set, strikethrough=true, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="●", style=StyleImpl{color=NamedTextColor{value="#5555ff"}, obfuscated=not_set, bold=not_set, strikethrough=true, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content=" ", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="SKY ", style=StyleImpl{color=NamedTextColor{value="#ffffff"}, obfuscated=not_set, bold=true, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="SERVERS ", style=StyleImpl{color=NamedTextColor{value="#55ffff"}, obfuscated=not_set, bold=true, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="●", style=StyleImpl{color=NamedTextColor{value="#5555ff"}, obfuscated=not_set, bold=not_set, strikethrough=true, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="---------------", style=StyleImpl{color=NamedTextColor{value="#555555"}, obfuscated=not_set, bold=not_set, strikethrough=true, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}, TextComponentImpl{content="●", style=StyleImpl{color=NamedTextColor{value="#5555ff"}, obfuscated=not_set, bold=not_set, strikethrough=true, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]} ( class net.kyori.adventure.text.TextComponentImpl): No cloner is suitable.
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:267) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1066) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1075) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[?:?]
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:260) ~[?:?]
13.05 17:05:39 [Server] INFO ... 33 more
13.05 17:05:39 [Server] ERROR Parameters: 
13.05 17:05:39 [Server] INFO net.minecraft.server.v1_16_R3.PacketPlayOutChat@6cddaa25[
13.05 17:05:39 [Server] INFO a=<null>
13.05 17:05:39 [Server] INFO components=<null>
13.05 17:05:39 [Server] INFO b=SYSTEM
13.05 17:05:39 [Server] INFO c=00000000-0000-0000-0000-000000000000
13.05 17:05:39 [Server] INFO ]
13.05 17:05:39 [Server] ERROR [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
13.05 17:05:39 [Server] INFO java.lang.RuntimeException: Failed to clone net.minecraft.server.v1_16_R3.PacketPlayOutChat@67926824 (class net.minecraft.server.v1_16_R3.PacketPlayOutChat) with com.comphenix.protocol.events.PacketContainer$2$1@3a381cd4
13.05 17:05:39 [Server] INFO at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:262) ~[?:?]
13.05 17:06:02 [Multicraft] Skipped 164 lines due to rate limit (60/s)`

Plugin version: 3.3.0.14
Server version: git-Airplane-"fad74c2" (MC: 1.16.5)

**Comment by LOOHP** [comment]
You need to use the latest ProtocolLib dev build (4.6.1-SNAPSHOT)

**Comment by baailey** [comment]
oh thanks
