### ISSUE TITLE
'Write a shorter message' Issue

### ISSUE THREAD

**Issue by joex92** [LOOHP/InteractiveChat#56]
I have the latest ProtocolLib, but every time I write a message too long (with no brakes, no mentions, just a plain message) it just shows me "Write a shorter message". I disabled the plugin to test if this plugins was the problem, tested, the message was shown, so I re-enabled it and now every single output to the chat get this error:
```
[Sat, 5. Jun 2021 03:22:21 UTC ERROR] [InteractiveChat] Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
[Sat, 5. Jun 2021 03:22:21 UTC ERROR] Parameters: 
  net.minecraft.server.v1_16_R3.PacketPlayOutChat@5e9596d2[
    a=TextComponent{text='', siblings=[TextComponent{text='Write a shorter message', siblings=[], style=Style{ color=red, bold=false, italic=false, underlined=false, strikethrough=false, obfuscated=false, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}
    components=<null>
    b=SYSTEM
    c=00000000-0000-0000-0000-000000000000
  ]
```
I know that maybe I shouldn't have re-enabled it without restarting, but that doesn't change the fact that this error pops up... 

Strangely enough the message is not shown in Minecraft chat but it is sent to discord chat (also using the discordsrv addon)...

**Comment by LOOHP** [comment]
Can you post the stacetrace of the error as well?

**Comment by joex92** [comment]
ok, so normally no `[ERROR]` message is sent to the console, I just confirmed it, when a message longer than 5 characters is sent by anyone on the Minecraft chat, the message seems to be intercepted and not sent to the. console, the message sent doesn't even appears in the console but it is sent to DiscordSRV... so I did this to get the `[ERROR]` message:
1. Use `/plugman disable InteractiveChat` to disable it
```
05.06 08:55:12 [Server] INFO Disabling InteractiveChat v3.3.0.21
05.06 08:55:12 [Server] INFO Unregistered placeholder expansion: interactivechat
05.06 08:55:12 [Server] INFO InteractiveChat has been Disabled!
05.06 08:55:12 [Server] INFO InteractiveChat has been disabled.
05.06 08:55:20 [Server] WARN java.lang.reflect.InvocationTargetException
05.06 08:55:20 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05.06 08:55:20 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05.06 08:55:20 [Server] WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05.06 08:55:20 [Server] WARN at java.base/java.lang.reflect.Method.invoke(Method.java:566)
05.06 08:55:20 [Server] WARN at com.loohp.interactivechat.modules.ProcessExternalMessage.processAndRespond(ProcessExternalMessage.java:84)
05.06 08:55:20 [Server] WARN at com.loohp.interactivechat.hooks.dynmap.DynmapCoreChatListener.chatEvent(DynmapCoreChatListener.java:38)
05.06 08:55:20 [Server] WARN at org.dynmap.common.DynmapListenerManager.processChatEvent(DynmapListenerManager.java:101)
05.06 08:55:20 [Server] WARN at org.dynmap.bukkit.DynmapPlugin$BukkitServer$3$1.run(DynmapPlugin.java:344)
05.06 08:55:20 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
05.06 08:55:20 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469)
05.06 08:55:20 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1514)
05.06 08:55:20 [Server] WARN at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:443)
05.06 08:55:20 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1423)
05.06 08:55:20 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1144)
05.06 08:55:20 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
05.06 08:55:20 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)
05.06 08:55:20 [Server] WARN Caused by: java.lang.ExceptionInInitializerError
05.06 08:55:20 [Server] WARN at com.loohp.interactivechat.modules.CustomPlaceholderDisplay.process(CustomPlaceholderDisplay.java:84)
05.06 08:55:20 [Server] WARN at com.loohp.interactivechat.modules.CustomPlaceholderDisplay.process(CustomPlaceholderDisplay.java:38)
05.06 08:55:20 [Server] WARN at com.loohp.interactivechat.modules.ProcessExternalMessage.processAndRespond0(ProcessExternalMessage.java:354)
05.06 08:55:20 [Server] WARN ... 16 more
05.06 08:55:20 [Server] WARN Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
05.06 08:55:20 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:542)
05.06 08:55:20 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:236)
05.06 08:55:20 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:232)
05.06 08:55:20 [Server] WARN at com.loohp.interactivechat.utils.PlaceholderParser.<clinit>(PlaceholderParser.java:31)
05.06 08:55:20 [Server] WARN ... 19 more```
2. send the message "1234567890" to test, and it was sent to the chat and appeared in the console
```
05.06 08:55:20 [Server] INFO [Lobby][Co-Owners] joex92 The Co-Owner: 1234567890
```
3. then re-enable the plugin with `/plugman enable InteractiveChat`
``` 
05.06 08:55:36 [Server] INFO Enabling InteractiveChat v3.3.0.21
05.06 08:55:36 [Server] WARN Enabled plugin with unregistered PluginClassLoader InteractiveChat v3.3.0.21
05.06 08:55:36 [Server] INFO Opened Sqlite database successfully
05.06 08:55:36 [Server] INFO InteractiveChat has hooked into Essentials!
05.06 08:55:36 [Server] INFO InteractiveChat has hooked into DiscordSRV!
05.06 08:55:36 [Server] INFO API listener com.loohp.interactivechat.hooks.discordsrv.DiscordSRVEvents subscribed (1 methods)
05.06 08:55:36 [Server] INFO InteractiveChat has injected into Dynmap!
05.06 08:55:36 [Server] INFO Successfully registered expansion: interactivechat
05.06 08:55:36 [Server] INFO InteractiveChat has been Enabled!
05.06 08:55:36 [Server] INFO InteractiveChat has been enabled.
05.06 08:55:36 [Server] INFO Loading languages...
05.06 08:55:36 [Server] INFO Loaded all 1 languages!
05.06 08:55:47 [Server] INFO CONSOLE issued server command: /list 
05.06 08:55:47 [Server] INFO Co-Owners: joex92The Co-Owner
```
4. Then tried to send the same message "1234567890" and got this:
```
05.06 08:56:01 [Server] ERROR Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
05.06 08:56:01 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class com.loohp.interactivechat.utils.PlaceholderParser
05.06 08:56:01 [Server] INFO at com.loohp.interactivechat.listeners.OutTabCompletePacket$1.onPacketSending(OutTabCompletePacket.java:90) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
05.06 08:56:01 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:522) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.DenizenNetworkManagerImpl.sendPacket(DenizenNetworkManagerImpl.java:179) ~[?:?]
05.06 08:56:01 [Server] INFO at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.DenizenNetworkManagerImpl.sendPacket(DenizenNetworkManagerImpl.java:162) ~[?:?]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$null$6(PlayerConnection.java:859) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
05.06 08:56:01 [Server] INFO at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
05.06 08:56:01 [Server] INFO at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:854) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1346) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1315) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1155) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:01 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
05.06 08:56:01 [Server] ERROR Parameters: 
05.06 08:56:01 [Server] INFO net.minecraft.server.v1_16_R3.PacketPlayOutTabComplete@703f77f8[
05.06 08:56:01 [Server] INFO a=4
05.06 08:56:01 [Server] INFO b=Suggestions{range=StringRange{start=6, end=11}, suggestions=[Suggestion{range=StringRange{start=6, end=11}, text='?', tooltip='null'}, Suggestion{range=StringRange{start=6, end=11}, text='joex92', tooltip='null'}, Suggestion{range=StringRange{start=6, end=11}, text='remove', tooltip='null'}, Suggestion{range=StringRange{start=6, end=11}, text='remove all', tooltip='null'}]}
05.06 08:56:01 [Server] INFO ]
05.06 08:56:03 [Multicraft] Skipped 42 lines due to rate limit (40/s)
05.06 08:56:03 [Server] WARN processChatEvent(PLAYER_CHAT,1234567890 ) - exception
05.06 08:56:03 [Server] ERROR Unhandled exception occured in onPacketSending(PacketEvent) for InteractiveChat
05.06 08:56:03 [Server] INFO java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@212bc48d[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@35ab0d9f[Wrapped task = com.loohp.interactivechat.listeners.OutChatPacket$1$$Lambda$10671/0x0000000841c31440@171dd371]] rejected from java.util.concurrent.ThreadPoolExecutor@74635df0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
05.06 08:56:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055) ~[?:?]
05.06 08:56:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825) ~[?:?]
05.06 08:56:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355) ~[?:?]
05.06 08:56:03 [Server] INFO at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) ~[?:?]
05.06 08:56:03 [Server] INFO at com.loohp.interactivechat.listeners.OutChatPacket.execute(OutChatPacket.java:97) ~[?:?]
05.06 08:56:03 [Server] INFO at com.loohp.interactivechat.listeners.OutChatPacket.access$100(OutChatPacket.java:70) ~[?:?]
05.06 08:56:03 [Server] INFO at com.loohp.interactivechat.listeners.OutChatPacket$1.onPacketSending(OutChatPacket.java:195) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:434) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:71) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:374) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:344) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
05.06 08:56:03 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
05.06 08:56:03 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.writePacket(NetworkManager.java:522) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:356) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.DenizenNetworkManagerImpl.sendPacket(DenizenNetworkManagerImpl.java:179) ~[?:?]
05.06 08:56:03 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2024) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1997) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.AbstractListenerPlayInImpl.sendPacket(AbstractListenerPlayInImpl.java:71) ~[?:?]
05.06 08:56:03 [Server] INFO at com.denizenscript.denizen.nms.v1_16.impl.network.handlers.DenizenPacketListenerImpl.sendPacket(DenizenPacketListenerImpl.java:84) ~[?:?]
05.06 08:56:03 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:235) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:251) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at me.kaizer.HoloChat.Events.PlayerChatPlaceHolderAPI.onChatEvent(PlayerChatPlaceHolderAPI.java:304) ~[?:?]
05.06 08:56:03 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor817.execute(Unknown Source) ~[?:?]
05.06 08:56:03 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.access$000(ChatProcessor.java:34) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:03 [Server] INFO at io.papermc.paper.adventure.ChatProcessor$1.evaluate(ChatProcessor.java:112) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
05.06 08:56:27 [Multicraft] Skipped 16 lines due to rate limit (40/s)
```

that's what happening... this error message are not generated normally, as I said, but only show to the player "Write a shorter message"

**Comment by joex92** [comment]
ok... I just found out the problem... my bad... I totally forgot I had [HoloChat](https://www.spigotmc.org/resources/✨-holochat-✨-new-hologram-chat-✅multiple-versions-✅-1-8-1-16.79821/) too, so that's what it's causing the error... weird, because the plugin shouldn't "disable" normal chat, I have that config disabled and max length is set on 50... well, maybe that's a thing for you to look up why both plugin can't work together, idk... I'm closing this here then...
