### ISSUE TITLE
Conflict with MythicCrucible

### ISSUE THREAD

**Issue by pkuliyi2015** [LOOHP/InteractiveChat#57]
MythicCrucible, an addon for MythicMobs, will mistakenly load a class from your plugin and cannot correctly work. Here is its report: 

[14:19:36] [Server thread/WARN]: [MythicCrucible] Loaded class org.apache.commons.lang3.tuple.Pair from InteractiveChat v3.3.0.21 which is not a depend, softdepend or loadbefore of this plugin.

and later, the MythicCrucible cannot correctly trigger skills when players use their weapons, and report the following signature error:

[14:19:37] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to MythicCrucible v0.0.1-SNAPSHOT
java.lang.LinkageError: loader constraint violation: when resolving method "io.lumine.xikage.mythicmobs.skills.TriggeredSkill.<init>(Lio/lumine/xikage/mythicmobs/skills/SkillTrigger;Lio/lumine/xikage/mythicmobs/skills/SkillCaster;Lio/lumine/xikage/mythicmobs/adapters/AbstractLocation;Lio/lumine/xikage/mythicmobs/adapters/AbstractEntity;Ljava/util/Collection;ZLjava/util/function/Consumer;[Lorg/apache/commons/lang3/tuple/Pair;)V" the class loader org.bukkit.plugin.java.PluginClassLoader @49f2a667 (instance of org.bukkit.plugin.java.PluginClassLoader, child of 'app' jdk.internal.loader.ClassLoaders$AppClassLoader) of the current class, io/lumine/mythiccrucible/items/EquippedItem, and the class loader org.bukkit.plugin.java.PluginClassLoader @5c5d2ce1 (instance of org.bukkit.plugin.java.PluginClassLoader, child of 'app' jdk.internal.loader.ClassLoaders$AppClassLoader) for the method's defining class, io/lumine/xikage/mythicmobs/skills/TriggeredSkill, have different Class objects for the type [Lorg/apache/commons/lang3/tuple/Pair; used in the signature
	at io.lumine.mythiccrucible.items.EquippedItem.runSkills(EquippedItem.java:38) ~[?:?]
	at io.lumine.mythiccrucible.profiles.Profile.runSkills(Profile.java:216) ~[?:?]
	at io.lumine.mythiccrucible.profiles.Profile.runSkills(Profile.java:165) ~[?:?]
...

Do you include a different version of  org.apache.commons in your plugin? I have unloaded your plugin now, and then MythicCrucible can work correctly. I have also tried to add a loadbefore: [InteractiveChat] in the plugin.yml of MythicCrucible, which also fixed the problem. By the way, an older version of InteractiveChat doesn't have this problem. 

However, I really hope that your plugin can fix the problem and work with MythicCrucible correctly.

Thanks very much!

**Comment by LOOHP** [comment]
Can you give this build a try? I've relocated the conflicted classes
[InteractiveChat-3.3.0.22.zip](https://github.com/LOOHP/InteractiveChat/files/6604047/InteractiveChat-3.3.0.22.zip)

**Comment by pkuliyi2015** [comment]
Really thanks for your quick reply! 

I tried but couldn't replicate my error locally (my remote server, which reported this problem, is running in a Java 11 environment but my local server is corretto-1.8). I will give you a report after the auto restart of my remote server tomorrow, but I guess the problem will only happen on very few servers with specific Java runtime, MythicCrucible, and have InteractiveChat loaded before MythicCrucible.

**Comment by pkuliyi2015** [comment]
I tested your InteractiveChat-3.3.0.22 and the problem has been successfully fixed. Thank you so much!
