### ISSUE TITLE
Some players are unable to join

### ISSUE THREAD

**Issue by Danielpeter-99** [LOOHP/InteractiveChat#6]
https://hasteb.in/umanamat.shell

Some players are unable to join for some reason, we tried many different things in the config and their versions but no results.

**Comment by LOOHP** [comment]
Are you sure it is due to InteractiveChat? What server software and version are you using?

**Comment by Danielpeter-99** [comment]
> Are you sure it is due to InteractiveChat? What server software and version are you using?

Yes, I had this issue before and had to get rid of InteractiveChat, that was months ago.

Tried re-installing to see if it'd work now but same issue.

I have the dependencies all on their latest builds & interactive chat (Just re-downloaded them all minutes ago) 

Servers are running: version git-Tuinity-"ed9e0c4" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by LOOHP** [comment]
I haven't really tried tunity before, maybe I'll give it a go. One thing you mentioned is that only some players cannot join, notice anything common with those players? Maybe a common rank, a common welcome message etc.?

**Comment by Danielpeter-99** [comment]
Not really, I tried looking for a pattern but nothing.
Tried making them all change versions, launchers, mods, no mods, and nothing worked.

The issue was solved as soon as I disabled InteractiveChat.

Let me know if there is anything I can do to help to test and solve the issue

**Comment by Danielpeter-99** [comment]
I have enabled a greater debugging on my bungee to see if the kick is related to bungee (Even though I don't use the bungee functions)

I use Aegis for my bungeecord.

Will be back tomorrow if I find anything

**Comment by LOOHP** [comment]
Do you use ViaVersion, if you do, you might want to take a look at the other issue as well (#7)

**Comment by Danielpeter-99** [comment]
I do use it, but I only allow 1.16.3 and 1.16.4

I believe that issue has to do with allowing very different versions

**Comment by LOOHP** [comment]
Yea but between 1.16.3 1.16.4, packets already need to be translated so they are different versions in the eyes of the Minecraft protocol

**Comment by Danielpeter-99** [comment]
I'll give it a try and will let you know!

**Comment by Danielpeter-99** [comment]
No viaversion, the issue is still happening

**Comment by LOOHP** [comment]
Are you running on the latest dev build?

**Comment by Danielpeter-99** [comment]
I was not, upon updating issue was solved (Even with Viaversion)
Thank you for your support!

**Comment by Danielpeter-99** [comment]
Apologize, players have reported to me (the ones that couldn't join before) that now their chat is grey-scaled
[https://i.imgur.com/gkyRwby.png](url)
[https://i.imgur.com/AkOdb8y.png](url)

**Comment by LOOHP** [comment]
Is it only happening to those players? 
If so, did they turn off colors in their client settings? (Options > Chat Settings > Colors)

**Comment by Danielpeter-99** [comment]
Yes, only them.
They did not. If they switch servers colors go back on

**Comment by LOOHP** [comment]
Colors appearing in other servers don't necessarily mean they didn't turn off colors tho.
As most servers do not respect this setting.

**Comment by Danielpeter-99** [comment]
I've asked them to check configs, will be back with their reply

**Comment by Danielpeter-99** [comment]
Correct! They fixed it. Thank you!
