### ISSUE TITLE
Plugin doesnt seem to work

### ISSUE THREAD

**Issue by Plasman888** [LOOHP/InteractiveChat#61]
I had the same issue as the guy in issue #45 but when i tried the fix the uuid didnt apear anymore but then the plugin didnt function. i have the discordsrv addon on aswell and that works flawlessly

**Comment by LOOHP** [comment]
Can you provide information like your server version, plugin version and errors in the console?

**Comment by Plasman888** [comment]
Oh yeah ofc

**Comment by Plasman888** [comment]
Latest log:https://pastebin.com/p07xasZQ
![Screenshot (105)](https://user-images.githubusercontent.com/71266194/122136569-55264900-ce75-11eb-9be0-ff11b600778f.png)

**Comment by Plasman888** [comment]
im currently using the latest spigot 1.17 version

**Comment by Plasman888** [comment]
> Latest log:https://pastebin.com/p07xasZQ
> ![Screenshot (105)](https://user-images.githubusercontent.com/71266194/122136569-55264900-ce75-11eb-9be0-ff11b600778f.png)

I was hovering over my name in this picture

**Comment by Plasman888** [comment]
> Can you provide information like your server version, plugin version and errors in the console?

I think you can see the plugin version but ye im using 4.00.2

**Comment by LOOHP** [comment]
You need to update placeholder api and its player, and server expansion to the dev build which supports 1.17. You can find them on their discord server
https://discord.com/invite/0utOOIYX82aImw7h

**Comment by Plasman888** [comment]
ok ill try that

**Comment by Plasman888** [comment]
Nice it works, i downloaded the dev build on their spigot page guess that wasnt the latest, thx man gr8 plugin
