### ISSUE TITLE
[Request/Bug?] UUID in EssentialsXDiscord

### ISSUE THREAD

**Issue by xamionex** [LOOHP/InteractiveChat#65]
EssentialsX devs recently published "EssentialsXDiscord" which has the same effect as DiscordSRV but some nicer features like the bot's icon and name being your player icon and name and such. Big problem though, in discord chat it has a conflict with IC and shows UUID in the chat
![image](https://user-images.githubusercontent.com/57235791/125533354-7b3c9772-7b85-4a58-ad71-34bb1fbc1885.png)

Any fixes or do i just switch to DiscordSRV for the time being? 
(ps. i tried removing <,> from chat plugin, tried adding them to conflict list in ic config, nothing worked)
Kind of related to #64

**Comment by LOOHP** [comment]
Support for EssentialsXDiscord will be coming on the next update.
