### ISSUE TITLE
Incompatibility on Arclight

### ISSUE THREAD

**Issue by ahdg6** [LOOHP/InteractiveChat#69]
https://github.com/IzzelAliz/Arclight/issues/336
https://paste.ubuntu.com/p/d5t4CZmhYM/

Tested with latest version of InteractiveChat Protocolib Arclight

**Comment by LOOHP** [comment]
Are you sure this is related to InteractiveChat? There is no mention of InteractiveChat in the stacktrace.

**Comment by LOOHP** [comment]
I've never heard of ArcLight, can you give me a link and some more information?

**Comment by ahdg6** [comment]
https://github.com/IzzelAliz/Arclight
It's a hybrid server for 1.15/1.16/1.17.
This issue only happen with InteractiveChat installed.

Thank you for your patience to investigate it.

**Comment by ahdg6** [comment]
Related code:https://github.com/IzzelAliz/Arclight/blob/1.16/arclight-common/src/main/java/io/izzel/arclight/common/mod/util/remapper/generated/RemappingURLClassLoader.java#L66

In my server,most of plugins run correctly, I don't know why InteractiveChat broke other plugins on Arclight. 
InteractiveChat is my favourite plugin and thank you for your work in advanced.

**Comment by LOOHP** [comment]
Since InteractiveChat does work on Bukkit and Spigot, it means that InteractiveChat should be properly coded for the Bukkit API. 

I think you should report it to ArcLight as well, as it means that there's something incompatible in how ArcLight implemented the Bukkit API.

**Comment by ahdg6** [comment]
This issue has been fixed by Arclight.
