### ISSUE TITLE
玩家一旦加入就顯示 disconnected with: You are sending too many packets!

### ISSUE THREAD

**Issue by Score2** [LOOHP/InteractiveChat#7]
我使用的是bungee + paper
bungee安裝了InteractiveChatBungee
paper有的安裝了InteractiveChat

在登錄服沒有安裝InteractiveChat
大廳服安裝InteractiveChat

一開始整個bungee + paper啟動，並沒有什麼異常
直到運行一段時間後，玩家加入服務器就被踢出並顯示You are sending too many packets!

而且僅在第一次加入子服時發生
比如玩家加入登錄服發生You are sending too many packets!
然後他再次加入登錄服就不會發生這種問題，但是他跳轉其他子服就會發生You are sending too many packets!，無論哪個子服有沒有安裝InteractiveChat

而且玩家一旦觸發了這個bug可以正常玩了，離線一段時間，再次加入又會觸發上面的bug，一直循環

23:37:20 [信息] [gkd,/0.0.0.0:25565] <-> InitialHandler has connected
23:37:22 [信息] [gkd] <-> ServerConnector [登录] has connected
23:37:23 [信息] [gkd] disconnected with: You are sending too many packets!
23:37:23 [信息] [gkd] -> UpstreamBridge has disconnected
23:37:23 [信息] [gkd] <-> DownstreamBridge <-> [登录] has disconnected
23:37:30 [信息] [gkd,/0.0.0.0:25565] <-> InitialHandler has connected
23:37:30 [信息] [gkd] <-> ServerConnector [登录] has connected
23:37:34 [信息] [gkd] <-> ServerConnector [大厅] has connected
23:37:34 [信息] [gkd] <-> DownstreamBridge <-> [登录] has disconnected
23:37:35 [信息] [gkd] disconnected with: You are sending too many packets!
23:37:35 [信息] [gkd] -> UpstreamBridge has disconnected
23:37:35 [信息] [gkd] <-> DownstreamBridge <-> [大厅] has disconnected
23:37:37 [信息] [gkd,/0.0.0.0:25565] <-> InitialHandler has connected
23:37:37 [信息] [gkd] <-> ServerConnector [登录] has connected
23:37:38 [信息] [gkd] <-> ServerConnector [大厅] has connected
23:37:38 [信息] [gkd] <-> DownstreamBridge <-> [登录] has disconnected

**Comment by LOOHP** [comment]
The kick message: `You are sending too many packets!` probably comes from ViaVersion.
Try increasing or disabling the `GLOBAL PACKET LIMITER` in the ViaVersion config [Both in bungeecord (if you've installed it one that) and spigot]

**Comment by Score2** [comment]
> The kick message: `You are sending too many packets!` probably comes from ViaVersion.
> Try increasing or disabling the `GLOBAL PACKET LIMITER` in the ViaVersion config [Both in bungeecord (if you've installed it one that) and spigot]
> 
> (And you probably need to install InteractiveChat on all spigot servers if you use the bungeecord mode)

ok
