### ISSUE TITLE
I don’t know when the error started, can you help me see it?

### ISSUE THREAD

**Issue by Zz-886** [LOOHP/InteractiveChat#71]
![image](https://user-images.githubusercontent.com/55978588/130060523-2117beef-d113-4b66-9f8b-64e24a0e1ec9.png)

**Comment by LOOHP** [comment]
How much ram did you give your server?

**Comment by Zz-886** [comment]
I tested locally so I allocated 4G

**Comment by LOOHP** [comment]
Does it work if the server just have InteractiveChat and its dependencies?

**Comment by Zz-886** [comment]
He still reported the error

**Comment by Zz-886** [comment]
![image](https://user-images.githubusercontent.com/55978588/130065520-0b060018-9009-4e05-bfbb-5de0c6dfb3ea.png)

**Comment by LOOHP** [comment]
Try keeping a backup of your config, and then let it generate a new one.

**Comment by Zz-886** [comment]
Regeneration can be loaded

**Comment by Zz-886** [comment]
Is this a bug?
![image](https://user-images.githubusercontent.com/55978588/130073486-9f71050f-97bc-4c13-b0f0-1f5073d6e56b.png)
![image](https://user-images.githubusercontent.com/55978588/130073557-13603db9-9ff1-4b2a-81cd-ef6f519c3ca4.png)

**Comment by LOOHP** [comment]
Not sure, I've never seen something like this before. Tell me if it ever happens again.

**Comment by Zz-886** [comment]
This is the first time I have encountered this kind of thing

**Comment by LOOHP** [comment]
Then it should be fine as long as it doesn't happen again. Feel free to reopen if it happens again.
