### ISSUE TITLE
AdvancedBan collision

### ISSUE THREAD

**Issue by ItzRonaldMLG** [LOOHP/InteractiveChat#73]
Server version: 1.17.1 (Bungee)
Sub Server(s): 1.17.1
Plugin version: 4.0.3.13

Hello,
I was testing another plugin and found this bug.
When trying to Temp-ban (ban works fine) i get this weird bug that edit the reason line to a long cmd=blablabla thing...
More info already send to AdvancedBan here: https://github.com/DevLeoko/AdvancedBan/issues/529
Because the plugin displaying the error was another plugin, i thought it was AdvancedBan. But it lastly comes from This plugin (InteractiveChat) after try and error.

!!! When i tested i found out it only happens if PlaceholderAPI is installed to !!!

**Comment by LOOHP** [comment]
Can you show me your InteractiveChat config on both bungeecord and sub servers?

**Comment by ItzRonaldMLG** [comment]
Bungee: https://pastebin.com/rCJpiXk3
Sub-servers: https://pastebin.com/Fb7TRpgH

**Comment by ItzRonaldMLG** [comment]
Any fix for this?

**Comment by ItzRonaldMLG** [comment]
Also for some reason i cant use the /tp <player> command.

**Comment by LOOHP** [comment]
> Bungee: https://pastebin.com/rCJpiXk3 Sub-servers: https://pastebin.com/Fb7TRpgH

In both of these configs, find the option `CommandsToParse`
Add a space in each regex expression like this:
`(?i)/message.*` -> `(?i)/message .*`
`(?i)/emsg.*` -> `(?i)/emsg .*`

**Comment by ItzRonaldMLG** [comment]
Hello, Welcome back online xD

Thanks for coming back and answering errors and questions!

It seems to have worked, at least i dont get the error anymore.
Thanks again for helping.

**Comment by LOOHP** [comment]
There seems to be a typo in your backend InteractiveChat config.
`SUGEST_COMMAND`
should be
`SUGGEST_COMMAND`

**Comment by ItzRonaldMLG** [comment]
Its fixed yes. Thank you!
