### ISSUE TITLE
CMI Direct Messages returning other players placeholders. 

### ISSUE THREAD

**Issue by LoJoSho** [LOOHP/InteractiveChat#75]
Using CMI direct message feature, such as /msg playername, and you put [item] or anything that can be pared by InteractiveChat, it will return to the player who sent the message the other players inventory or item.

Example of me (LoJoSho) sending [inv] to Bordig, https://i.imgur.com/VxGVpIm.gif and getting Bordigs inventory in return, even though he never sent it. 

Version:
1.17.1 PurPur

IC Version:
4.0.3.13

**Comment by LOOHP** [comment]
You need to add /cmi msg into the CommandToParse option in the config
