### ISSUE TITLE
[i] is no longer working in recent Paper versions

### ISSUE THREAD

**Issue by mind04** [LOOHP/InteractiveChat#77]
With recent paper versions [i] and friends are no longer working in interactive chat. In the chat they are no longer replaced by the correct value. After some investigation I found the paper commit responsible for the changed behavior: https://github.com/PaperMC/Paper/commit/857524864847552e74029c1351e8791206aeb919

Paper version 1.17.1-326 is the last one without issues

**Comment by loohpjames** [comment]
You do not use any chat formatting plugin, correct? i.e. you still have the `<Player> Hello!` formatting?
