### ISSUE TITLE
Placeholder not working for player name

### ISSUE THREAD

**Issue by alfiejfs** [LOOHP/InteractiveChat#78]
![image](https://user-images.githubusercontent.com/42497992/145093150-90742ad5-9d13-4a5a-9b25-ba890a092d73.png)
![image](https://user-images.githubusercontent.com/42497992/145093168-ed66f2ca-5207-4113-8e75-df5d3909c17e.png)

1.18 Paper

**Comment by LOOHP** [comment]
You have to download the required placeholder expansions from placeholderapi.
`/papi ecloud download player`
