### ISSUE TITLE
I can see others players inventories

### ISSUE THREAD

**Issue by Maksim-Lipenka** [LOOHP/InteractiveChat#80]
Players on my server can see each others inentories with /pm [player] [inv]
They can see inventories of players who received a message(but if I write /pm [player] [inv] I should see my inv).
P.S. It can't be reproduced by admin(idk why)
You can test it on my server(not ad): mc.just-survive.ru
Thanks
plugins version: 4.0.4.3

**Comment by LOOHP** [comment]
You have to add your msg command and all of its alias to the CommandToParse option in the config

**Comment by Maksim-Lipenka** [comment]
@LOOHP thank you for so quick help!
