### ISSUE TITLE
Clearing chat causes server to stop responding. 

### ISSUE THREAD

**Issue by hemanth4121** [LOOHP/InteractiveChat#81]
**Version:**
[17:04:17 INFO]: This server is running Purpur version git-Purpur-"9a7a4dc" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a7a4dc on ver/1.17.1)

**InteractiveChat Version:**
4.0.4.10

**Issue:**
Executing the /cc or /clearchat command causes server to stop responding.

**Log:**
[message.txt](https://github.com/LOOHP/InteractiveChat/files/7717863/message.txt)

**Comment by LOOHP** [comment]
Can you give this build a try?
https://drive.google.com/file/d/1f3OtOcUy2hp6GBYuZPKiA5sVRbQm1ImT/view?usp=sharing

**Comment by hemanth4121** [comment]
I'll try it out today, will update again shortly

**Comment by LOOHP** [comment]
Thank you!

**Comment by hemanth4121** [comment]
Hey, so the players in my server are reporting the chat messages not being sent properly sometimes, and they can't view it as well. I've tried to recreate, and sure enough when the TPS dips some chat messages don't get sent/get sent but we don't know it's sent etc.   

Here's a spark report, although I'm not sure if it's helping with much. 
https://spark.lucko.me/S02XqgP0z0

Do let me know if I need to send any more information.

**Comment by LOOHP** [comment]
But does that build solve server freezing when the chat clears?

**Comment by LOOHP** [comment]
This build sends chat messages on a separate thread, maybe it will help. 
https://drive.google.com/file/d/1-Y42A9pdv81__nK6812KQaabV6AZUbB4/view?usp=sharing
(Do you use the discordsrv addon? This build might not be compatible with the version you are using. I can send you one that is compatible if you want)

**Comment by hemanth4121** [comment]
> But does that build solve server freezing when the chat clears?
I had my moderator test it out, they used cmi clearchat and it didnt get executed at all, forgot to mention that. 

I don't use the discordsrv addon, as I'm yet to test it out further in my dev server. 
I'll try this new build to see if it changes anything.

**Comment by hemanth4121** [comment]
> This build sends chat messages on a separate thread, maybe it will help. https://drive.google.com/file/d/1-Y42A9pdv81__nK6812KQaabV6AZUbB4/view?usp=sharing (Do you use the discordsrv addon? This build might not be compatible with the version you are using. I can send you one that is compatible if you want)

I updated to this build, apparently it doesn't clear the chat yet, I'll have to see if players still face issues w the message sending/delivering.

**Comment by LOOHP** [comment]
That is weird, does the player sending message not delivered bug happen with the build that crashes the server when you clear chat? Or is it only introduced once you try these test builds?

**Comment by LOOHP** [comment]
My third attempt: https://drive.google.com/file/d/1-Y42A9pdv81__nK6812KQaabV6AZUbB4/view?usp=sharing

**Comment by hemanth4121** [comment]
> That is weird, does the player sending message not delivered bug happen with the build that crashes the server when you clear chat? Or is it only introduced once you try these test builds?

It's only with the test builds. I'll update further in a few more hours when we have more players on the server to verify if it's still the case, and will update the build too.

**Comment by LOOHP** [comment]
If you haven't tried the last build yet, try this one instead: https://drive.google.com/file/d/1-Y42A9pdv81__nK6812KQaabV6AZUbB4/view?usp=sharing

**Comment by hemanth4121** [comment]
> If you haven't tried the last build yet, try this one instead: https://drive.google.com/file/d/1-Y42A9pdv81__nK6812KQaabV6AZUbB4/view?usp=sharing

I just updated to this version, I was asleep sorry couldn't check out the other build yet. But the second attempt build posed this issue, according to one of my moderators.

My staff are reporting that keywords are not working, I tested it via console as well. I had [bal], [inv] etc enabled as well as some custom keywords.

**Comment by LOOHP** [comment]
Do they not work all the time or sometimes?

**Comment by hemanth4121** [comment]
Not at all, apparently.

**Comment by LOOHP** [comment]
Are there any errors in the console?

**Comment by hemanth4121** [comment]
Hey, apologies for the very late response. I was caught up irl. Everything works fine now apparently, after that server restarted. One issue I've noticed is, even with the air block thing disabled in settings if  players `/msg` each other the `[item]` keyword where one of them is holding nothing, they can see the other person's held item as well if they're holding something.

**Comment by LOOHP** [comment]
You need to add your msg command and all its alias to the CommandToParse option in the config.

**Comment by hemanth4121** [comment]
Noted, I'll try it out tomorrow.

**Comment by hemanth4121** [comment]
Update - it worked, once again apologies as I had irl commitments. Thanks for all the help!
