### ISSUE TITLE
Private messages allows to view another inventory/enderchest

### ISSUE THREAD

**Issue by exzolink** [LOOHP/InteractiveChat#83]
By sending a tag in private messages, you can view the inventory of the player to whom the message was sent 
Tested with VentureChat

**Comment by LOOHP** [comment]
You have to add your msg command and all its aliases to the CommandToParse option in the config.

**Comment by exzolink** [comment]
It did not help

**Comment by LOOHP** [comment]
Are you on bungeecord? If you are, you need to do that to all backend server configs and on bungee as well

**Comment by exzolink** [comment]
I use plugin only on backend server, bungee mode disabled and plugin not installed on bungee

**Comment by LOOHP** [comment]
Then is your VentureChat cross server?

**Comment by exzolink** [comment]
Yes

**Comment by LOOHP** [comment]
But then if a player on a server with i sends a messages to a player on another server with ic, ic wouldn't be able to handle it logically

**Comment by exzolink** [comment]
Is it possible fully disable parsing for /msg and aliases?

**Comment by LOOHP** [comment]
It is not possible atm.
