### ISSUE TITLE
EssentialsX Discord Integration?

### ISSUE THREAD

**Issue by satadrive420** [LOOHP/InteractiveChat#84]
Hello!

Are there any plans to add EssentialsX Discord integration? I would like to switch away from DiscordSRV, but I would love to keep the features from InteractiveChat.

**Comment by LOOHP** [comment]
InteractiveChat does work with EssentialsX Discord, tho InteractiveChatDiscordSrvAddon obviously doesn't, and there are no plans to port it to EssentialsX Discord atm, as DiscordSRV is still much more powerful.
