### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by satadrive420** [LOOHP/InteractiveChat#85]
Using the latest version of InteractiveChat, players were able to take items from the GUI.

**Comment by LOOHP** [comment]
Which version is "the latest version"?

**Comment by satadrive420** [comment]
Dupe was present under version 4.1.1.2.

https://www.youtube.com/watch?v=_7c836Q5oEk

**Comment by LOOHP** [comment]
Confirmed.

**Comment by LOOHP** [comment]
Can you give InteractiveChat 4.1.1.14 a try?

**Comment by satadrive420** [comment]
It looks like this issue is fixed on our test environment. I will push this to our production environment and check,

**Comment by satadrive420** [comment]
Issue is fixed.
