### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by ItzRonaldMLG** [LOOHP/InteractiveChat#89]
Error: https://pastebin.com/ULAV8pak
Config: https://pastebin.com/Vjb737ex

Also:
- How can i add multiple aliases?
- Did i do this emoji correct?
- Can i also replace chat text like <3 to a ❤️ ? like my other question but without :

**Comment by LOOHP** [comment]
Try redownloading 4.1.2.0 and then reset the config.

1. It's a regex match, so you can match all your aliases in the regex
2. Which emoji are you referring to?
3. Yes you can, you just have to create a CustomPlaceholder that matches the text based heart and replace with emoji heart.

**Comment by ItzRonaldMLG** [comment]
I might know were the error is: you cant use '':'' in keyword?
With this my question 2 is answered xD it doesnt work yet. 

1. Like this? ''(?i)\\[Placeholder1\\]|\\[Placeholder2\\]'' 
    or
    Aliases: ''(?i)\\[Placeholder2\\]"
2. The one in the config i send.
3. I tried multiple things, every time i get errors like the first i reported. 
    I did it like i did in the config on the bottom i send in the first report.
    Do you suggest how to do it? Tried like 3 different ways getting only errors..
    I would like 2 methodes for players:
    :Heart: and <3
    Because there are multiple you will only remember with text instate of all those ¯\_(ツ)_/¯ and so on xD

**Comment by LOOHP** [comment]
1. Like this `''(?i)\\[Placeholder1\\]|\\[Placeholder2\\]''` (`\` needs to be escaped in double quotes in yaml)
2. Like (1.), Aliases had been removed.
3. Incase of :Heart: and <3, it'll be
```yaml
Keyword: "(?i):Heart:|<3"
```

**Comment by ItzRonaldMLG** [comment]
2. In the default config there is still alias used at placeholder 5,6,7 ;)
3. i tried this and got the same error as the first message: https://pastebin.com/EVUgnKAa
   Also the ❤️ got replaced like you can see.
   Did i do something wrong or does the plugin not support this codes xD

**Comment by LOOHP** [comment]
2. You can remove those options, they don't do anything anymore
3. Try escaping the heart emoji `\u2764\uFE0F`
Also your `Click:` is indented incorrectly

**Comment by ItzRonaldMLG** [comment]
It works now, Thank you very much!
