### ISSUE TITLE
Invalid Item can't be fixed

### ISSUE THREAD

**Issue by dellise26** [LOOHP/InteractiveChat#9]
Hello, firstly i had like to thanks you for this plugin, flexible as we wish and very complete, i like it so much and it's free, thanks.
So to introduce my error, i use MMOItems and they modify item with nbttag ( at least i think so ), and when i try to display an item, it say "invalid Item", it's not my plugin i can't modify it ( and don't want to ), but i don't know why it does that, as you display an item with modified nbttag in the description on spigot i don't know why it does that.
Here i will send you the modified item, i hope it is fixable, thanks
![image](https://user-images.githubusercontent.com/38770349/103233359-3b339100-493d-11eb-89d7-345b9aa93236.png)
![image](https://user-images.githubusercontent.com/38770349/103233379-4981ad00-493d-11eb-91b9-6b806634c315.png)
Btw the inventory display it correctly

**Comment by LOOHP** [comment]
Emm.. Do you use plugins like ViaVersion?

**Comment by dellise26** [comment]
yes i use ViaVersion, and no indeed i'm 1.16 on server but 1.12 with client, isn't there a way to have it even if ViaVersion is used ?

**Comment by LOOHP** [comment]
It is the job of ViaVersion to do the nbt version conversion, just like how the items in the inventory display correctly over different versions. However, ViaVersion doesn't seem to covert Item NBT display in chat messages. Perhaps it is a "missing feature" in ViaVersion?

**Comment by dellise26** [comment]
ok so i need to ask them to push that 😭 , i will wait 1 month then, but before that to be sure, i will try in 1.16 to be sure it is not MMOItems

**Comment by dellise26** [comment]
ok after verification, it is indeed ViaVersion, thanks for helping 🙇
