### ISSUE TITLE
strange characters

### ISSUE THREAD

**Issue by SheerYin** [LOOHP/InteractiveChat#90]
This is the modified configuration
[config.txt](https://github.com/LOOHP/InteractiveChat/files/8028544/config.txt)

but once I reboot it becomes
[config.txt](https://github.com/LOOHP/InteractiveChat/files/8028550/config.txt)

Whether I try to save as UTF-8 or GBK, it always converts to gibberish

**Comment by LOOHP** [comment]
Which version of InteractiveChat are you using?

**Comment by LOOHP** [comment]
I see you are using 4.1.2.0, this bug should be fixed for a while already. Try updating to the latest dev builds.

**Comment by SheerYin** [comment]
Update to the latest version solved
