### ISSUE TITLE
Item name not respecting custom display name

### ISSUE THREAD

**Issue by mio9** [LOOHP/InteractiveChat#92]
When sharing item into the chat, custom item names are not respected and get replaced by the original item name. While the custom item name is displayed when hovered, the name is directly replaced by its vanilla item name on discord which causes confusion.

![image](https://user-images.githubusercontent.com/11581624/160752048-49e4478c-482d-4c42-a967-c74f21915494.png)
![image](https://user-images.githubusercontent.com/11581624/160752250-5fe01ee0-7ca0-45b4-87c5-ca0e5f25a7bb.png)
![image](https://user-images.githubusercontent.com/11581624/160753355-b606e3d2-6275-4773-8bbc-8ab8b81e1cef.png)

**Comment by LOOHP** [comment]
Which version of InteractiveChat are you using?

**Comment by mio9** [comment]
Fixed as of 4.1.4.8, closing issue now
