### ISSUE TITLE
People can acquire ghost items from viewing another player's item, inventory and enderchest and use them, causing server-side anticheats to trigger

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [LOOHP/InteractiveChat#94]
Here's the video that shows the demonstration
https://cdn.discordapp.com/attachments/903872838535098409/964176164337881098/Nitrous89_on_Minecraft_Server_2022-04-14_21-32-05.mp4

People can acquire the items by shifting or pressing F to put that item into their left hand and use them as normal

This can cause anticheats to trigger as the player is actually using a ghost item to do illegal movements

**Comment by LOOHP** [comment]
Can you try this with other plugin inventory menus with a trident?

**Comment by QuanTrieuPCYT** [comment]
> Can you try this with other plugin inventory menus with a trident?

i only have this inventory plugin lol

**Comment by LOOHP** [comment]
Emm ok, I've just tested this and I can confirm this is a thing. However, this is probably not a bug in InteractiveChat, it is most likely a client - server desync problem that exists in Minecraft. You can try reporting this to Minecraft, SpigotMC or if you do use, PaperMC.
