### ISSUE TITLE
Unable to parse placeholder..

### ISSUE THREAD

**Issue by Beartherter13** [LOOHP/InteractiveChat#98]
Unable to parse placeholder.. Written when i use in chat [item] , this problem some with [inv] etc
How fix it 

And in console : 
[InteractiveChat] Failed to check against "api.loohpjames.com" for the latest version.. It could be an internet issue or "api.loohpjames.com" is down. If you want disable the update checker, you can disable in config.yml, but we still highly-recommend you to keep your plugin up to date!

**Comment by Beartherter13** [comment]
Minecraft ver 1.15.2 .
last ver all api

**Comment by LOOHP** [comment]
That error you can safely ignore.

As for the issue you are having, I've laid out how to deal with that in the pins in the #interactivechat channel on my [discord server](http://dev.discord.loohpjames.com)
